<?php
use CongViec\Entity\CongViec;
use CongViec\Entity\TheoDoi;


	if ($this->flashMessenger()->hasMessages()) 
	{
    	echo '<div class="ui positive message">
  				<i id="btFm" class="close icon"></i>
  				<div class="header">';

    	$messages = $this->flashMessenger()->getMessages();
    	foreach($messages as $message) {
        	echo $message;
    	}
    	echo '</div></div>';

    	echo '
	    <script type="text/javascript">
	        setTimeout(function(){
	            document.getElementById("btFm").click();
	        },5000);
	    </script>';
    }	
?>
<div class="ui top attached tabular menu">
  <a class="active item" data-tab="first">Thông tin chi tiết</a>
  <a class="item" data-tab="second">Cập nhật</a>
</div>
<div class="ui bottom attached active tab segment" data-tab="first">
<?php
	echo 'Tên công việc'.$congViec->getTen().'<br>';
	echo 'Tên người tạo'.$congViec->getNguoiTao()->getUsername().'<br>';
	echo 'Nội dung'.$congViec->getNoiDung().'<br>';
	echo 'Trích yếu' .$congViec->getTrichYeu().'<br>';
	echo 'Ngày ban hànhs' .$congViec->getNgayBanHanh()->format('d-m-Y').'<br>';
	echo 'Ngày hoàn thành' .$congViec->getNgayHoanThanh()->format('d-m-Y').'<br>';
	echo 'Trạng thái' .$congViec->getTrangThaiNhom().'<br>';
?>
</div>
<div class="ui bottom attached tab segment" data-tab="second">
 <?php
 	$form->setAttribute('action', $this->url('cong_viec/crud', array('action'=>'chi-tiet-cong-viec','id'=>$congViec->getId())));
	$form->prepare();
	echo $this->form()->openTag($form);
	$capNhatCongViec=$form->get('congViecs');
	echo $this->formHidden($capNhatCongViec->get('id'));
	echo $this->formRow($capNhatCongViec->get('ten'));
	echo $this->formRow($capNhatCongViec->get('noiDung'));
	echo $this->formRow($capNhatCongViec->get('loai'));	
	echo $this->formRow($capNhatCongViec->get('ngayBanHanh'));
	echo $this->formRow($capNhatCongViec->get('ngayHoanThanh'));
	echo $this->formRow($capNhatCongViec->get('dinhKem'));
	//die(var_dump($congViec->getDinhKems()));

	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag();
	?>
</div>
<?php
if($congViec->getDinhKems())
	{
 ?>		
 		 Danh sách file đính kèm
		 <table>
		 	<thead>
		 		<tr>
		 			<th>
		 				Tên file
		 			</th>
		 			<th>
		 				STT
		 			</th>
		 			<th>
		 				Hủy
		 			</th>
		 		</tr>
		 	</thead>
		 	<tbody>
		 	<?php
		 	$stt=0;
		 	$ymd=$congViec->getNgayTao()->format('Y/m/d');
		 	foreach ($congViec->getDinhKems() as $dinhKem) {
		 		$explodes=explode('_',$dinhKem->getUrl());
				$fileName='';							
				foreach ($explodes as $key => $explode) {
					if($key>0)
					{
						$fileName.=$explode;
					}								
				}
		 	?>
		 		<tr>
		 			<td>
		 				<?php $stt++; echo $stt; ?>
		 			</td>
		 			<td>
	 				<?php 
						$link=$this->basePath().'/filedinhkems/'.$ymd.'/'.$dinhKem->getUrl();
						echo '<a href="'.$link.'">'.$fileName.'</a>'; 
					?>
		 			</td>
		 			<td>
		 				<a href="<?php echo $this->url('cong_viec/crud',array('action'=>'xoa-dinh-kem','id'=>$dinhKem->getId())); ?>"><i class="large inverted red trash icon"></i></a>
		 			</td>
		 		</tr>
		 	<?php
		 	}
		 	?>
		 		
		 	</tbody>
		 </table>
<?php
	}
?>
Danh sách báo cáo
<table>
	<thead>
        <tr>
			<th>Nội dung</th>
			<th>Ngày báo cáo</th>
			<th>Người báo cáo</th>
			<th>Đính kèm</th>
			<th>hủy</th>
		</tr>
	</thead>
	<tbody>
	<?php
	foreach ($theoDois as $theoDoi) {
		if($theoDoi->getTrangThai()==TheoDoi::DA_HUY){
			echo '<tr class="lightred">';
		}
		else{
			echo '<tr>';
		}
		
			echo '<td>'; 
				echo $theoDoi->getNoiDung();
			echo '</td>';

			echo '<td>';
				echo $theoDoi->getNgayBaoCao()->format('d-m-Y');
			echo '</td>';

			echo '<td>';
				echo $theoDoi->getNguoiBaoCao()->getUsername();
			echo '</td>';
			echo '<td>'; ?>
				<table>
				<?php
				$ymd=$theoDoi->getNgayBaoCao()->format('Y/m/d');
				
				
				foreach ($theoDoi->getDinhKems() as $dinhKem) { ?>
					<tr>
						<td>
						<?php 
							$explodes=explode('_',$dinhKem->getUrl());
							$fileName='';							
							foreach ($explodes as $key => $explode) {
								if($key>0)
								{
									$fileName.=$explode;
								}								
							}
							
							$link=$this->basePath().'/filedinhkems/'.$ymd.'/'.$dinhKem->getUrl();
							echo '<a href="'.$link.'">'.$fileName.'</a>'; 
						?>
						</td>
					</tr>
				<?php	
				}
				?>
				
				</table>
			<?php 
			echo '</td>'; ?>
			<td>
				<a href="<?php echo $this->url('theo_doi/crud',array('action'=>'huy-bao-cao','id'=>$theoDoi->getId())); ?>"><i class="large inverted red trash icon"></i></a>
			</td>
		<?php
		echo '</tr>';

	}
	?>
		
	</tbody>
</table>
<?php 
	if($congViec->getTrangThai()==CongViec::HOAN_THANH||$congViec->getTrangThai()==CongViec::TRE_HAN)
	{?>
		<input type="submit" value="Hoàn thành">&nbsp;<input type="submit" value="Báo cáo mới">
	<?php
	}
	else{ ?>
		
		<a href="<?php echo $this->url('cong_viec/crud',array('action'=>'hoanThanh','id'=>$congViec->getId())); ?>"><input type="submit" value="Hoàn thành"></a>
		<a href="<?php echo $this->url('theo_doi/crud',array('action'=>'baoCaoMoi','id'=>$congViec->getId())); ?>"><input type="submit" value="Báo cáo mới"></a>
	<?php
	}
?>


<script type="text/javascript">
	$(document).ready(function(){
		$('.menu .item').tab();
		$('.message .close').on('click', function() {
		  $(this).closest('.message').fadeOut();
		});
	})

</script>