<?php
use CongViec\Entity\CongViec;
use CongViec\Entity\TheoDoi;


	if ($this->flashMessenger()->hasMessages()) 
	{
    	echo '<div class="ui positive message">
  				<i id="btFm" class="close icon"></i>
  				<div class="header">';

    	$messages = $this->flashMessenger()->getMessages();
    	foreach($messages as $message) {
        	echo $message;
    	}
    	echo '</div></div>';

    	echo '
	    <script type="text/javascript">
	        setTimeout(function(){
	            document.getElementById("btFm").click();
	        },5000);
	    </script>';
    }	
?>
<div class="sixteen wide column row"><h3>Chi tiết công việc</h3></div>	
<div class="ui top attached tabular menu">
  <a class="active item" data-tab="first">Thông tin chi tiết</a>
  <a class="item" data-tab="second">Cập nhật</a>
</div>
<div class="ui bottom attached active tab segment" data-tab="first">
	<table class="ui compact celled definition table">
		<tr>
			<td class="collapsing">
				Tên công việc
			</td>
			<td>
			<?php echo $congViec->getTen(); ?>
			</td>
		</tr>
		<tr>
			<td class="collapsing">
				Nội dung
			</td>
			<td>
			<?php echo $congViec->getNoiDung(); ?>
			</td>
		</tr>
		<tr>
			<td class="collapsing">
				Trích yếu
			</td>
			<td>
			<?php echo $congViec->getTrichYeu(); ?>
			</td>
		</tr>
		<tr>
			<td class="collapsing">
				Ngày ban hành
			</td>
			<td>
			<?php echo $congViec->getNgayBanHanh()->format('Y-m-d'); ?>
			</td>
		</tr>
		<tr>
			<td class="collapsing">
				Hạn xử lý
			</td>
			<td>
			<?php echo $congViec->getNgayHoanThanh()->format('Y-m-d'); ?>
			</td>
		</tr>
		<tr>
			<td class="collapsing">
				Người tạo
			</td>
			<td>
			<?php echo $congViec->getNguoiTao()->getHo().' '.$congViec->getNguoiTao()->getTen(); ?>
			</td>
		</tr>
		<tr>
			<td class="collapsing">
				Đính kèm
			</td>
			<td>
			<?php
				$ymd=$congViec->getNgayTao()->format('Y/m/d');
			 	foreach ($congViec->getDinhKems() as $soFile => $dinhKem) {
			 		if($soFile>0){
			 			echo ' | ';
			 		}
			 		$explodes=explode('_',$dinhKem->getUrl());
					$fileName='';							
					foreach ($explodes as $key => $explode) {
						if($key>0)
						{
							$fileName.=$explode;
						}								
					}
					$link=$this->basePath().'/filedinhkems/'.$ymd.'/'.$dinhKem->getUrl();
					echo '<a href="'.$link.'">'.$fileName.'</a>'; 
				}
			?>
			</td>
		</tr>
		<tr>
			<td class="collapsing">
				Trạng thái
			</td>
			<td 
			<?php
			if($congViec->getTrangThaiNhom()=='Chưa xem'){
				echo 'class="blue"';
			}elseif ($congViec->getTrangThaiNhom()=='Đang xử lý') {
				echo 'class="purple"';
			}
			elseif ($congViec->getTrangThaiNhom()=='Hoàn thành') {
				echo 'class="green"';
			}
			elseif ($congViec->getTrangThaiNhom()=='Trễ hạn') {
				echo 'class="lightred"';
			}
			?>
			>
			<?php echo $congViec->getTrangThaiNhom(); ?>
			</td>
		</tr>
	</table>
</div>
<div class="ui bottom attached tab segment" data-tab="second">
 <?php
 	$form->setAttribute('action', $this->url('cong_viec/crud', array('action'=>'chi-tiet-cong-viec','id'=>$congViec->getId())));
	$form->prepare();
	echo $this->form()->openTag($form);
	$capNhatCongViec=$form->get('congViecs');
	echo $this->formHidden($capNhatCongViec->get('id'));
?>
	<div class="ui form">
		<div class="fields">
			<div class="sixteen wide field">
			<?php echo $this->formRow($capNhatCongViec->get('ten')); ?>
			</div>
		</div>
		<div class="fields">
			<div class="sixteen wide field">
			<?php echo $this->formRow($capNhatCongViec->get('noiDung')); ?>
			</div>
		</div>
		<div class="fields">
			<div class="sixteen wide field">			
			<?php 
				$capNhatCongViec->get('loai')->setAttribute('class','ui dropdown selection fluid');
				echo $this->formRow($capNhatCongViec->get('loai'));	 
			?>
			</div>
		</div>
		<div class="fields">
			<div class="sixteen wide field">
			<?php echo $this->formRow($capNhatCongViec->get('ngayBanHanh')); ?>
			</div>
		</div>
		<div class="fields">
			<div class="sixteen wide field">
			<?php echo $this->formRow($capNhatCongViec->get('ngayHoanThanh')); ?>
			</div>
		</div>
		
			<div class="ui divided selection list">
			  <div class="item">
			    <b>Đính kèm: </b>
			    
			  
			<?php
				$ymd=$congViec->getNgayTao()->format('Y/m/d');
			 	foreach ($congViec->getDinhKems() as $soFile => $dinhKem) {
			 		if($soFile>0){
			 			echo ' | ';
			 		}
			 		$explodes=explode('_',$dinhKem->getUrl());
					$fileName='';							
					foreach ($explodes as $key => $explode) {
						if($key>0)
						{
							$fileName.=$explode;
						}								
					}
					$link=$this->basePath().'/filedinhkems/'.$ymd.'/'.$dinhKem->getUrl(); ?>
					<a href="<?php echo $link ?>" class="blue"><?php echo $fileName; ?></a>&nbsp;&nbsp;
					<a href="<?php echo $this->url('cong_viec/crud',array('action'=>'xoa-dinh-kem','id'=>$dinhKem->getId())); ?>">Hủy</a>
				<?php
				}
			?>
			
		</div>
		</div>
		<div class="fields">
			<div class="sixteen wide field">
			<?php echo $this->formRow($capNhatCongViec->get('dinhKem')); ?>
			</div>
		</div>

		<div class="sixteen wide column row right aligned">
			<div class="fields">
				<div class="sixteen wide field">
				<?php 
					$form->get('submit')->setAttribute('class','ui button blue');
					echo $this->formSubmit($form->get('submit')); ?>
				</div>
			</div>
		</div>
	</div>
	<?php
	echo $this->form()->closeTag();
	?>
</div>
<div class="sixteen wide column row"><h3>Danh sách các báo cáo quá trình</h3></div>	

<table  class="ui table">
	<thead>
        <tr>
			<th>Nội dung</th>
			<th>Ngày báo cáo</th>
			<th>Người tạo báo cáo</th>
			<th>Đính kèm</th>
			<th>Hủy</th>
		</tr>
	</thead>
	<tbody>
	<?php
	foreach ($theoDois as $theoDoi) {
		if($theoDoi->getTrangThai()==TheoDoi::DA_HUY){
			echo '<tr class="lightred">';
		}
		else{
			echo '<tr>';
		}
		
			echo '<td>'; 
				echo $theoDoi->getNoiDung();
			echo '</td>';

			echo '<td>';
				echo $theoDoi->getNgayBaoCao()->format('d-m-Y');
			echo '</td>';

			echo '<td>';
				echo $theoDoi->getNguoiTao()->getHo().' '.$theoDoi->getNguoiTao()->getTen();
			echo '</td>';
			echo '<td>'; ?>
				<!-- <table> -->
				<?php
				$ymd=$theoDoi->getNgayBaoCao()->format('Y/m/d');
				
				
				foreach ($theoDoi->getDinhKems() as $soFile => $dinhKem) { ?>
				<?php 
					if($soFile>0){
						echo ' | ';
					}
					$explodes=explode('_',$dinhKem->getUrl());
					$fileName='';							
					foreach ($explodes as $key => $explode) {
						if($key>0)
						{
							$fileName.=$explode;
						}								
					}
					
					$link=$this->basePath().'/filedinhkems/'.$ymd.'/'.$dinhKem->getUrl();
					echo '<a href="'.$link.'">'.$fileName.'</a>'; 						
				}
				?>				
				<!-- </table> -->
			<?php 
			echo '</td>'; ?>
			<td>
				<a href="<?php echo $this->url('theo_doi/crud',array('action'=>'huy-bao-cao','id'=>$theoDoi->getId())); ?>"><i class="large inverted red trash icon"></i></a>
			</td>
		<?php
		echo '</tr>';

	}
	?>
		
	</tbody>
</table>
<?php 
	if($congViec->getTrangThai()==CongViec::HOAN_THANH||$congViec->getTrangThai()==CongViec::TRE_HAN)
	{?>
		<div class="sixteen wide column row right aligned">
			<input type="submit" value="Hoàn thành" class="ui button green">&nbsp;
			<input type="submit" value="Báo cáo mới" class="ui button blue">
		</div>
	<?php
	}
	else{ ?>
		<div class="sixteen wide column row right aligned">
			<input type="submit" id="btnHoanThanh" value="Hoàn thành" class="ui button green">&nbsp;
			<input type="submit" id="btnBaoCaoMoi" value="Báo cáo mới" class="ui button blue">
		</div>
	<?php
	}
?>
<form id="frmHoanThanh" action="<?php echo $this->url('cong_viec/crud',array('action'=>'hoan-thanh','id'=>$congViec->getId())); ?>">
</form>

<form id="frmBaoCaoMoi" action="<?php echo $this->url('theo_doi/crud',array('action'=>'bao-cao-moi','id'=>$congViec->getId())); ?>">
</form>

<script type="text/javascript">
	$(document).ready(function(){
		$('.menu .item').tab();
		$('.message .close').on('click', function() {
		  $(this).closest('.message').fadeOut();
		});
		$('#btnHoanThanh').on('click',function(){
			$('#frmHoanThanh').submit();
		});
		$('#btnBaoCaoMoi').on('click',function(){
			$('#frmBaoCaoMoi').submit();
		});
		$('.ui.dropdown').dropdown();
	});

</script>