<h1>Giao việc</h1>
<?php
$form->setAttribute('action', $this->url('cong_viec/crud', array('action'=>'giao-viec')));
$form->prepare();?>

<?php
echo $this->form()->openTag($form);
$congVan = $form->get('cong-van');?>
<div class="ui grid">
	<div class="ui form eight wide column">
		<h4 class="ui dividing header">Công văn</h4>
		<div class="field">
			<?php echo $this->formRow($congVan->get('soHieu')); ?>
		</div>
		<div class="field">
			<?php echo $this->formRow($congVan->get('ngayBanHanh'));?>
		</div>
		<div class="field">
			<?php echo $this->formRow($congVan->get('nguoiKy'));?>
		</div>
		<div class="field">
			<?php echo $this->formRow($congVan->get('trichYeu'));?>
		</div>
		<div class="field">
			<?php echo $this->formRow($congVan->get('dinhKem'));?>
		</div>		
		<div class="field">
			<?php echo $this->formCollection($congVan->get('congViecs'));?>
		</div>

		<?php echo $this->formHidden($form->get('csrf')); ?>
		<div class="field">
			<?php echo $this->formSubmit($form->get('submit')); ?>
		</div>
		<?php echo $this->form()->closeTag();?>
	</div>
</div>