<?php echo $this->partial('template/flash_current'); ?>
<?php $form->setAttribute('action', $this->url('cong_viec/crud', array('action'=>'giao-viec')));
$form->prepare();?>

<?php echo $this->form()->openTag($form);
$congViec = $form->get('congViec');
$congVan = $congViec->get('cha');?>
<div class="ui form">
	<div class="ui celled grid">
		<!-- <div class="row">
			<div class="eight wide column">
				<h2 class="ui header"><span><i class="plus icon"></i></span> GIAO VIỆC MỚI</h2>
			</div>
		</div> -->
		<div class="row">
			<div class="ten wide column">
				<?php $user =  $this->zfcUserIdentity();?>
				<?php $nguoiTao = $congViec->get('nguoiTao'); ?>
				<?php $nguoiTao->setAttribute('value', $user->getId()) ?>
				<?php echo $this->formHidden($nguoiTao); ?>
				<div class="two fields">
					<div class="field">
						<?php echo $this->formLabel($congViec->get('loai')); ?>
			          	<?php echo $this->formElement($congViec->get('loai')); ?>
			          	<?php echo $this->formElementErrors($congViec->get('loai')); ?>
					</div>
					<div class="field">
						<?php echo $this->formLabel($congViec->get('linhVuc')); ?>
			          	<?php echo $this->formElement($congViec->get('linhVuc')); ?>
			          	<?php echo $this->formElementErrors($congViec->get('linhVuc')); ?>
			        </div>
				</div>
				<div class="field reset able">
					<?php echo $this->formLabel($congViec->get('ten')); ?>
		          	<?php echo $this->formElement($congViec->get('ten')); ?>
		          	<?php echo $this->formElementErrors($congViec->get('ten')); ?>
				</div>
				<div class="two fields">
					<div class="field">
						<?php echo $this->formLabel($congViec->get('ngayBanHanh')); ?>
			          	<?php echo $this->formJqxDate($congViec->get('ngayBanHanh')); ?>
			          	<?php echo $this->formElementErrors($congViec->get('ngayBanHanh')); ?>
					</div>
					<div class="field">
						<?php echo $this->formLabel($congViec->get('ngayHoanThanh')); ?>
			          	<?php echo $this->formJqxDate($congViec->get('ngayHoanThanh')); ?>
			          	<?php echo $this->formElementErrors($congViec->get('ngayHoanThanh')); ?>
					</div>
				</div>
				<div class="field reset able">
					<?php echo $this->formLabel($congViec->get('noiDung')); ?>
		          	<?php echo $this->formElement($congViec->get('noiDung')); ?>
		          	<?php echo $this->formElementErrors($congViec->get('noiDung')); ?>
				</div>			
			</div>
			<div class="six wide column">
				<?php echo $this->formHidden($congVan->get('id')); ?>
				<div class="field">
					<?php echo $this->formLabel($congVan->get('soHieu')); ?>
		          	<?php echo $this->formElement($congVan->get('soHieu')); ?>
		          	<?php echo $this->formElementErrors($congVan->get('soHieu')); ?>
				</div>
				<div class="field">
					<?php echo $this->formLabel($congVan->get('ngayBanHanh')); ?>
		          	<?php echo $this->formJqxDate($congVan->get('ngayBanHanh')); ?>
		          	<?php echo $this->formElementErrors($congVan->get('ngayBanHanh')); ?>
				</div>
				<div class="field">
					<?php echo $this->formLabel($congVan->get('nguoiKy')); ?>
		          	<?php echo $this->formElement($congVan->get('nguoiKy')); ?>
		          	<?php echo $this->formElementErrors($congVan->get('nguoiKy')); ?>
				</div>
				<div class="field">
					<?php echo $this->formLabel($congVan->get('trichYeu')); ?>
		          	<?php echo $this->formElement($congVan->get('trichYeu')); ?>
		          	<?php echo $this->formElementErrors($congVan->get('trichYeu')); ?>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="eight wide column">
				<div class="field reset able">
					<?php echo $this->formLabel($congViec->get('dinhKems')); ?>
		          	<?php echo $this->formElement($congViec->get('dinhKems')); ?>
		          	<?php echo $this->formElementErrors($congViec->get('dinhKems')); ?>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="eight wide column">
				<div class="field">
					<label>Thực hiện</label>
					
					<div class="ui pointing secondary menu">
					  	<a class="active item" data-tab="first">Cá nhân</a>
					  	<a class="item" data-tab="second">Đơn vị</a>
					  	<a class="item" data-tab="thrid">Nhóm</a>
					</div>					
					<div class="ui bottom attached active tab" data-tab="first">
						<div class="ui left icon input">
						  	<input placeholder="Tìm người thực hiện..." type="text" id="jstree_s">
						  	<i class="search icon"></i>
						</div>
						<div class="jstree"></div>	
					</div>
					<div class="ui bottom attached tab" data-tab="second">
						<div class="ui left icon input">
						  	<input placeholder="Tìm đơn vị thực hiện..." type="text" >
						  	<i class="search icon"></i>
						</div>
						<div id="don-vi-list" class="ui list"></div>
					</div>
					<div class="ui bottom attached tab" data-tab="thrid">
					  	<div class="ui left icon input">
						  	<input placeholder="Tìm nhóm thực hiện..." type="text" id="jstree_s_nhom">
						  	<i class="search icon"></i>
						</div>
						<div id="nhom-list" class="ui list"></div>
					</div>
				</div>
			</div>
			<div class="eight wide column">
				<div class="field">
					<label>Phân công <i id="phan_lai" class="circular undo link icon" title="Phân công lại"></i></label>
					<?php $nguoiThucHiens = $congViec->get('nguoiThucHiens'); ?>
					<div id="event_result">
						<?php echo $this->formCollection($nguoiThucHiens); ?>
						<div class="template ui hidden">
						    <?php echo $this->vaiTro(); ?>
						    <i class="remove icon link"></i>
						    <!-- <img class="ui avatar image" src="<?php echo $this->basePath();?>/img/square-image.png"> -->
						    <div class="content">
						     	__ten__
						    </div>
						</div>
						<div class="ui list divided"></div>
					</div>
				</div>
			</div>
		</div>
			
		<div class="row">
			<div class="sixteen wide column">
				<div class="field">
					<div class="ui checkbox">
				      	<input type="checkbox">
				      	<label>Công việc khẩn</label>
				    </div>
				</div>
				<div class="field">
					<?php echo $this->formSubmit($form->get('submit')); ?>
				</div>
			</div>
			<?php echo $this->formHidden($form->get('csrf')); ?>
		</div>
	</div>
</div>
<?php echo $this->form()->closeTag();?>
<script type="text/javascript">
	// @todo xu ly phan cong trung nhau
	$.ajax({
   		type : 'post',
   		dataType : 'json',
   		url : "<?php echo $this->url('cong_viec/crud', array('action'=>'ajax-get-nhom-nguoi-dung')) ?>",
   		success : function(data){
   			$.each(data, function(key, val){
   				$('#nhom-list').append('<div class="item pointer" data-id="'+val.id+'"><i class="disabled users icon link"></i><div class="content">'+val.text+' ('+val.count+')</div><div class="ui hidden val list"></div></div>');
   				$.each(val.children, function(k, v){
   					$('#nhom-list [data-id="'+val.id+'"] .val.list').append('<div class="item"><span>'+v.id+'</span><span>'+v.text+'</span></div>');
   				});
   			});
   		}
   	});

   	$('#nhom-list').on('dblclick', '.item', function(){
   		$(this).find('.val.list .item').each(function(){
   			var id = $(this).find('span:eq(0)').text();
   			var ten = $(this).find('span:eq(1)').text();
   			add_phan_cong(id, ten);
   		});
   	});

   	$.ajax({
   		type : 'post',
   		dataType : 'json',
   		url : "<?php echo $this->url('cong_viec/crud', array('action'=>'ajax-get-don-vi')) ?>",
   		success : function(data){
   			$.each(data, function(key, val){
   				$('#don-vi-list').append('<div class="item pointer" data-id="'+val.id+'"><i class="disabled users icon link"></i><div class="content">'+val.text+'</div><div class="ui hidden val list"></div></div>');
   				$.each(val.children, function(k, v){
   					$('#don-vi-list [data-id="'+val.id+'"] .val.list').append('<div class="item"><span>'+v.id+'</span><span>'+v.text+'</span></div>');
   				});
   			});
   		}
   	});

   	$('#don-vi-list').on('dblclick', '.item', function(){
   		$(this).find('.val.list .item').each(function(){
   			var id = $(this).find('span:eq(0)').text();
   			var ten = $(this).find('span:eq(1)').text();
   			add_phan_cong(id, ten);
   		});
   	});

	var currentCount = 0;
	$('.jstree').jstree({
		'core' : {
			'data' : {
				"url" : "<?php echo $this->url('cong_viec/crud', array('action'=>'ajax-get-to-chuc')) ?>",
				"dataType" : "json" // needed only if you do not supply JSON headers
			}
		},
		"plugins" : [ "search" ]
	}).bind("dblclick.jstree", function (event) {
	   var node = $(event.target).closest("li");
	   var id = node.attr('id');
	   var ten = node.text();
	   if(isNaN(id)){
	   	alert('Vui lòng chọn nhân viên để phân công');
	   }
	   else{
	   	add_phan_cong(id, ten);
	   }
	});

	var to = false;
	$('#jstree_s').keyup(function () {
	    if(to) { clearTimeout(to); }
	    to = setTimeout(function () {
	      	var v = $('#jstree_s').val();
	      	$('.jstree').jstree(true).search(v);
	    }, 250);
	});

	$('#phan_lai').click(function(){
		$('#event_result > .list').empty();
		$('#event_result > fieldset > div').remove();
	});

	$('#event_result').on('click', '.remove.icon', function(){
		var id = $(this).closest('.item').attr('id').substring(3);
		$('#event_result > .list > #pc_'+id).remove();
		$('#event_result > fieldset > #fs_'+id).remove();
	});

	$('.reset.able :input')
	 	.val('')
	 	.removeAttr('checked')
	 	.removeAttr('selected');
	$('#event_result > fieldset > div').remove();
	

	function add_phan_cong(id, ten) {
        //var currentCount = $('#event_result > fieldset > fieldset').length;
        currentCount++;
        var template = $('#event_result > fieldset > span').data('template');
        template = template.replace(/__index__/g, currentCount);

        $('#event_result > fieldset').prepend('<div id="fs_'+currentCount+'">' + template + '</div>');

        ///////
        var template = $('#event_result .template').html();
	   	template = template.replace(/__ten__/g, ten);
	   	$('#event_result .list').append('<div id="pc_'+currentCount+'" class="item">' + template + '</div>');
	   	$('input[name="congViec[nguoiThucHiens]['+currentCount+'][vaiTro]"]').val(<?php echo \CongViec\Entity\PhanCong::PHOI_HOP; ?>);
	   	$('input[name="congViec[nguoiThucHiens]['+currentCount+'][nguoiThucHien][id]"]').val(id);
	   	$('#pc_'+currentCount+' .ui.dropdown')
	        .dropdown({
	        	onChange: function (val) {
	        		if(!isNaN(val)){
	        			$('input[name="congViec[nguoiThucHiens]['+currentCount+'][vaiTro]"]').val(val);
	        		}
			    }
	        });

        return currentCount;
    }

    $('#loai-cong-viec').dropdown({ //loại luồng
    	onChange: function (val) {
    		if(!isNaN(val)){
    			$.ajax({
    				type: 'post',
    				dataType: 'json',
    				url: '<?php echo $this->url('danh_muc/crud', array('action'=>'so-ngay-thuc-hien')) ?>',
    				data: {
    					'id': val
    				},
    				success: function(data){
    					var cur = new Date(),
    					time = cur.setDate(cur.getDate() + data.soNgay);
    					date = new Date(time);
    					$('#congViecngayHoanThanh.form-date .jqxDate').jqxDateTimeInput('setDate', date);
    				}
    			});
    		}
	    }
    });
</script>