<div class="divView">        
  
  <div class="ui grid">           
    <div class="sixteen wide column fluid"></div>
    <div class="sixteen wide column fluid"></div>
  </div>
  <form method="post" action="<?php echo $this->url('cong_viec/crud',array('action'=>'index')); ?>">
    <div class="ui form">
      <div class="inline fields">
        <div class="field">
          <div class="ui large label">Tìm theo hạn xử lý - từ ngày</div>
          <input type="date" style="height:33px;" name="tuNgay" id="tuNgay">
        </div>
        <div class="field">
          <label class="ui large label"> đến ngày</label>
          <input type="date" style="height:33px;" name="denNgay" id="denNgay">
        </div>
        <div class="field">
          <input type="submit" class="ui blue button"  style="width:130px;" name="btnSubmit" id="btnTimTheoNgay" value="Tìm theo ngày">
        </div>
      </div>
     </div>
   <!-- </form> -->

   <div class="ui grid">   
    <div class="four column row">
      <div class="four wide column">
        <input type="hidden" name="dieuKienLoc" value="<?php echo $dieuKienLoc; ?>">
        <div class="ui radio checkbox" id="radioLocChuaXem"><input type="radio" name="locTheoTrangThai"><label>Công việc chưa xử lý (10)</label></div>            
      </div>
      <div class="four wide column">
        <div class="ui radio checkbox" id="radioLocDangXuLy"><input type="radio" name="locTheoTrangThai"><label>Công việc đang xử lý (10)</label></div>     
      </div>
      <div class="four wide column">
        <div class="ui radio checkbox" id="radioLocTreHan"><input type="radio" name="locTheoTrangThai"><label>Công việc bị quá hạn (10)</label></div>           
      </div>
      <div class="four wide column">
        <div class="ui radio checkbox" id="radioLocTatCa"><input type="radio" name="locTheoTrangThai" checked="checked"><label>Tất cả các công việc (40)</label></div>         
      </div>
    </div>
   <!--  <form method="post" action="<?php echo $this->url('cong_viec/crud',array('action'=>'index')); ?>"> -->
    <div class="sixteen wide column">
      <div class="ui menu">
        <div class="menu">
          <div class="item">
            Tìm nhanh
          </div>
          <div class="ui pointing dropdown link item">
            <i class="dropdown icon"></i>
            <span class="text">Chọn chủ đề</span>
            <div class="menu">              
              <div class="item" id="ten">Chủ đề</div>
              <div class="item" id="nguoiTao">Người tạo</div>             
              <!-- <div class="item" id="ngayHoanThanh">Hạn xử lý</div>  -->
            </div>
          </div>
          <div class="item">
            <div class="ui icon input">
              <input type="hidden" value="ten" id="dieuKien" name="dieuKien">
              <input type="text" placeholder="Search..." style="width:370px;" id="txtDuLieu" name="txtDuLieu">
              <i class="search icon"></i>
            </div>
          </div>
          <div class="right item">
            <input type="submit" class="tiny ui button" name="btnSubmit" id="btnTim" value="Tìm">
            <input type="submit"  class="tiny ui button" name="btnSubmit" id="btnXemHet" value="Xem hết">
          </div>
          
        </div>
      </div>
    </div>
    </form>
    <div class="sixteen wide column fluid">
      <table class="ui table" id="tblTatCa">
        <thead>
          <tr>
            <th>Người tạo công việc</th>
            <th>Chủ đề</th>
            <th>Hạn xử lý</th>            
          </tr>
        </thead>
        <tbody>
        <?php
          foreach ($congViecs as $congViec) {
            if($congViec->getTrangThaiNhom()!='Hoàn thành')
            {
              if($congViec->getTrangThaiNhom()=='Chưa xem')
              {
                echo '<tr class="blue">';                
              }
              elseif($congViec->getTrangThaiNhom()=='Đang xử lý')
              {
                echo '<tr class="purple">';
              }
              elseif($congViec->getTrangThaiNhom()=='Trễ hạn')
              {
                echo '<tr class="lightred">';
              }
              else
              {
                echo '<tr>';
              } 
                echo '<td>'.$congViec->getNguoiTao()->getUsername().'</td>';
                echo '<td>'.$congViec->getTen().'</td>';
                echo '<td>'.$congViec->getTrangThaiNhom().$congViec->getNgayHoanThanh()->format('d-m-Y').'</td>';
              echo '</tr>';
            }
              
          }
        ?>          
        </tbody>
      </table>
      <table class="ui table" id="tblChuaXem" hidden="true">
        <thead>
          <tr>
            <th>Người tạo công việc</th>
            <th>Chủ đề</th>
            <th>Hạn xử lý</th>            
          </tr>
        </thead>
        <tbody>
        <?php
          foreach ($congViecs as $congViec) {
            if($congViec->getTrangThaiNhom()=='Chưa xem')
            {
              echo '<tr>'; 
                echo '<td>'.$congViec->getNguoiTao()->getUsername().'</td>';
                echo '<td>'.$congViec->getTen().'</td>';
                echo '<td>'.$congViec->getNgayHoanThanh()->format('d-m-Y').'</td>';
              echo '</tr>';          
            }        
               
          }
        ?>          
        </tbody>
      </table>
      <table class="ui table" id="tblDangXuLy" hidden="true">
        <thead>
          <tr>
            <th>Người tạo công việc</th>
            <th>Chủ đề</th>
            <th>Hạn xử lý</th>            
          </tr>
        </thead>
        <tbody>
        <?php
          foreach ($congViecs as $congViec) {
            if($congViec->getTrangThaiNhom()=='Đang xử lý')
            {
              echo '<tr>'; 
                echo '<td>'.$congViec->getNguoiTao()->getUsername().'</td>';
                echo '<td>'.$congViec->getTen().'</td>';
                echo '<td>'.$congViec->getNgayHoanThanh()->format('d-m-Y').'</td>';
              echo '</tr>';          
            }          
               
          }
        ?>          
        </tbody>
      </table>
      <table class="ui table" id="tblTreHan" hidden="true">
        <thead>
          <tr>
            <th>Người tạo công việc</th>
            <th>Chủ đề</th>
            <th>Hạn xử lý</th>            
          </tr>
        </thead>
        <tbody>
        <?php
          foreach ($congViecs as $congViec) {
            if($congViec->getTrangThaiNhom()=='Trễ hạn')
            {
              echo '<tr>'; 
                echo '<td>'.$congViec->getNguoiTao()->getUsername().'</td>';
                echo '<td>'.$congViec->getTen().'</td>';
                echo '<td>'.$congViec->getNgayHoanThanh()->format('d-m-Y').'</td>';
              echo '</tr>';          
            }          
               
          }
        ?>          
        </tbody>
      </table>
    </div>
    <div class="right aligned sixteen wide column">                  
      <table align="right">
        <tr style="text-align:left;">
          <td>
            <div class="ui blue empty circular label"></div>
          </td>
          <td>
            <span style="color:blue;">&nbsp;Chưa xem</span>
          </td>
        </tr>
        <tr style="text-align:left;">
          <td>
            <div class="ui purple empty circular label"></div>
          </td>
          <td>
            <span style="color:purple;">&nbsp;Đang xử lý</span>
          </td>
        </tr> 
        <tr style="text-align:left;">
          <td>
            <div class="ui green empty circular label"></div>
          </td>
          <td>
            <span style="color:green;">&nbsp;Hoàn thành</span>
          </td>
        </tr>                    
        <tr style="text-align:left;">
          <td>
            <div class="ui red empty circular label"></div>
          </td>
          <td>
            <span style="color:red;">&nbsp;Trễ hạn</span>
          </td>
        </tr> 
      </table>              
    </div>
  </div>
</div>

<script type="text/javascript">

  $(document).ready(function(){
    $('.dropdown').dropdown();
    $('#radioLocTatCa').on('click',function(){
      showTable('#tblTatCa');
      $('#dieuKienLoc').val('radioLocTatCa');
    });
    $('#radioLocChuaXem').on('click',function(){
      showTable('#tblChuaXem');
      $('#dieuKienLoc').val('radioLocChuaXem');
    });
    $('#radioLocDangXuLy').on('click',function(){
      showTable('#tblDangXuLy');
      $('#dieuKienLoc').val('radioLocDangXuLy');
    });
    $('#radioLocTreHan').on('click',function(){
      showTable('#tblTreHan');
      $('#dieuKienLoc').val('radioLocTreHan');
    });

    if($('#dieuKienLoc').val()==''){
      $('#dieuKienLoc').val('radioLocTatCa');
      var id='#'.$('#dieuKienLoc').val();
      $(id).attr('checked', true);
    }
    else
    {
      var id='#'.$('#dieuKienLoc').val();
      $(id).attr('checked', true);
    }


    $('#ten').on('click',function(){
      $('#dieuKien').val('ten');
    });
    $('#nguoiTao').on('click',function(){
      $('#dieuKien').val('nguoiTao');
    });
    $('#ngayHoanThanh').on('click',function(){
      $('#dieuKien').val('ngayHoanThanh');
    });
    $('#btnTim').on('click',function(){
      if($('#txtDuLieu').val()==''||$('#txtDuLieu').val()==null)
      {
        return false;
      }
      return true;
    });
    $('#btnTimTheoNgay').on('click',function(){
      if($('#tuNgay').val()==''&&$('#denNgay').val()=='')
      {
        return false;
      }
      return true;
    });
  });
    
</script>