<?php $congVan = $congViec->getCongVan(); ?>
<div class="ui celled grid">
	<div class="row">
		<div class="sixteen wide column">
			<div class="ui divided horizontal list">
			  	<div class="item">
			  		Ngày hết hạn: <strong><?php echo $congViec->getNgayHoanThanh()->format('d/m/Y'); ?></strong>
			  	</div>
			  	<div class="item">
			  		Loại: <strong><?php echo $congViec->getLoaiLabel(); ?></strong>
			  	</div>
			  	<div class="item">
			  		Lĩnh vực: <strong><?php echo $congViec->getLinhVucLabel(); ?></strong>
			  	</div>
			</div>		
			<!-- <a href="#" class="ui small button right floated">
			  	In công việc
			</a> -->
			<a href="<?php echo $this->url('theo_doi/crud', array('action'=>'bao-cao', 'id'=>$congViec->getId())) ?>" class="ui small button right floated <?php echo $congViec->isHoanThanh()?'disabled':''; ?>">
			  	Tạo báo cáo
			</a>	
			<!-- <a href="<?php echo $this->url('theo_doi/crud', array('action'=>'nghiem-thu', 'id'=>$congViec->getId())) ?>" class="ui green animated fade small button right floated <?php echo $congViec->isHoanThanh()?'disabled':''; ?>">
			  	<div class="visible content">Nghiệm thu</div>
			  	<div class="hidden content">Hoàn thành</div>
			</a> -->		
		</div>
	</div>
	<div class="row">
		<div class="sixteen wide column">
			<h3 class="ui header"><?php echo $congViec->getTen(); ?>
				<?php if($congViec->isHoanThanh()): ?>
					<div class="ui red horizontal label">Hoàn thành</div>
				<?php endif; ?>
			</h3>
			<div class="ui divider"></div>
			<p><?php echo $congViec->getNoiDung(); ?></p>
			<?php if($dinhKems = $congViec->getDinhKems()): ?>
				<p>
					<u>Đính kèm:</u> 
		   			<?php
						$ymd = $congViec->getNgayTao()->format('Y/m/d');
					 	foreach ($dinhKems as $soFile => $dinhKem) {
					 		if($soFile>0){
					 			echo ' | ';
					 		}
					 		$explodes=explode('_',$dinhKem->getUrl());
							$fileName='';							
							foreach ($explodes as $key => $explode) {
								if($key>0)
								{
									$fileName.=$explode;
								}								
							}
							$link=$this->basePath().'/filedinhkems/'.$ymd.'/'.$dinhKem->getUrl();
							echo '<a href="'.$link.'">'.$fileName.'</a>'; 
						}
					?>
				</p>
			<?php endif; ?>
			<div class="ui divider"></div>
			<?php $baoCaos = $congViec->getBaoCaos(); ?>
			<div class="ui list">
				<div class="item">
					<div class="content">
						<div class="header">Danh sách báo cáo</div>
						<div class="ui divided selection list">
			  			<?php foreach($baoCaos as $baoCao): ?>
			  				<div class="item">
			  					<?php if($baoCao->getNguoiTao()->getId() == $this->zfcUserIdentity()->getId()): ?>
								<div class="ui dropdown edit right floated">
								  <i class="angle down icon"></i>
								  <div class="menu">
								  	<div class="item" data-value="huy" data-href="<?php echo $this->url('theo_doi/crud', array('action'=>'huy-bao-cao', 'id'=>$baoCao->getId())) ?>">Hủy báo cáo</div>
								  	<div class="item" data-value="sua">Chỉnh sửa báo cáo</div>
								  </div>
								</div>
								<?php endif; ?>
			  					<i class="top aligned right triangle icon"></i>
			  					<div class="content">
								   	<div class="description">
								   		<i><?php echo $baoCao->getTenNguoiTao(); ?> - <?php echo $baoCao->getNgayBaoCao()->format('d/m/Y') ?></i>
								   		<div><?php echo $baoCao->getNoiDung(); ?></div>
								   		<?php if($dinhKems = $baoCao->getDinhKems()): ?>
									   		<div>
									   			<u>Đính kèm:</u> 
									   			<?php
													$ymd = $baoCao->getNgayBaoCao()->format('Y/m/d');
												 	foreach ($dinhKems as $soFile => $dinhKem) {
												 		if($soFile>0){
												 			echo ' | ';
												 		}
												 		$explodes=explode('_',$dinhKem->getUrl());
														$fileName='';							
														foreach ($explodes as $key => $explode) {
															if($key>0)
															{
																$fileName.=$explode;
															}								
														}
														$link=$this->basePath().'/filedinhkems/'.$ymd.'/'.$dinhKem->getUrl();
														echo '<a href="'.$link.'">'.$fileName.'</a>'; 
													}
												?>
									   		</div>
									   	<?php endif; ?>
								   	</div>
								</div>
			  				</div>
			  			<?php endforeach; ?>
			  			</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$('.ui.dropdown.edit').dropdown({
    	onChange: function (val, txt, ele) {
    		var item = $(this).closest('.item');
    		if(val == 'huy'){
    			var href = ele.data('href');
    			$.ajax({
    				type: 'post',
    				dataType: 'json',
    				url: href,
    				success: function(data){
    					if(data.status == 'success'){
    						item.remove();
    					}
    				}
    			});
    		}
    		else{

    		}
	    }
    });
</script>