<?php $form->setAttribute('action', $this->url('danh_muc/crud', array('action' => 'sua-linh-vuc', 'id' => $id)));
$form->prepare();
$taxonomy = $form->get('taxonomy');
$term = $taxonomy->get('term');
echo $this->form()->openTag($form);?>

<div class="ui form">
	<div class="ui celled grid">
		<div class="row">
        	<div class="sixteen wide column">
    			<div class="field">
    				<?php $term->get('name')->setLabel('Lĩnh vực'); ?>
    				<?php echo $this->formLabel($term->get('name')); ?>
		          	<?php echo $this->formElement($term->get('name')); ?>
		          	<?php echo $this->formElementErrors($term->get('name')); ?>
    			</div>
    			<div class="field">
    				<?php $taxonomy->get('description')->setLabel('Mô tả') ?>
    				<?php echo $this->formLabel($taxonomy->get('description')); ?>
		          	<?php echo $this->formElement($taxonomy->get('description')); ?>
		          	<?php echo $this->formElementErrors($taxonomy->get('description')); ?>
    			</div>
        		<div class="field">
        			<?php echo $this->formHidden($term->get('slug'));?>
        			<?php echo $this->formHidden($form->get('csrf'));?>
        			<?php $form->get('submit')->setValue('Lưu thông tin') ?>
        			<?php echo $this->formSubmit($form->get('submit')); ?>
        		</div>
        	</div>
        </div>
    </div>
</div>
