<?php

namespace DoctrineORMModule\Proxy\__CG__\CongViec\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TheoDoi extends \CongViec\Entity\TheoDoi implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'ngayBaoCao', 'nguoiBaoCao', 'nguoiTao', 'noiDung', 'congVan', 'dinhKems', 'trangThai');
        }

        return array('__isInitialized__', 'id', 'ngayBaoCao', 'nguoiBaoCao', 'nguoiTao', 'noiDung', 'congVan', 'dinhKems', 'trangThai');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TheoDoi $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function onPrePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', array());

        return parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNgayBaoCao($ngayBaoCao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNgayBaoCao', array($ngayBaoCao));

        return parent::setNgayBaoCao($ngayBaoCao);
    }

    /**
     * {@inheritDoc}
     */
    public function getNgayBaoCao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNgayBaoCao', array());

        return parent::getNgayBaoCao();
    }

    /**
     * {@inheritDoc}
     */
    public function setNguoiBaoCao($nguoiBaoCao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNguoiBaoCao', array($nguoiBaoCao));

        return parent::setNguoiBaoCao($nguoiBaoCao);
    }

    /**
     * {@inheritDoc}
     */
    public function getNguoiBaoCao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNguoiBaoCao', array());

        return parent::getNguoiBaoCao();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoiDung($noiDung)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoiDung', array($noiDung));

        return parent::setNoiDung($noiDung);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoiDung()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoiDung', array());

        return parent::getNoiDung();
    }

    /**
     * {@inheritDoc}
     */
    public function setCongVan($congVan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCongVan', array($congVan));

        return parent::setCongVan($congVan);
    }

    /**
     * {@inheritDoc}
     */
    public function getCongVan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCongVan', array());

        return parent::getCongVan();
    }

    /**
     * {@inheritDoc}
     */
    public function addDinhKems($dinhKems)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDinhKems', array($dinhKems));

        return parent::addDinhKems($dinhKems);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDinhKems($dinhKems)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDinhKems', array($dinhKems));

        return parent::removeDinhKems($dinhKems);
    }

    /**
     * {@inheritDoc}
     */
    public function getDinhKems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDinhKems', array());

        return parent::getDinhKems();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrangThai($trangThai)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrangThai', array($trangThai));

        return parent::setTrangThai($trangThai);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrangThai()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrangThai', array());

        return parent::getTrangThai();
    }

    /**
     * {@inheritDoc}
     */
    public function setNguoiTao($nguoiTao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNguoiTao', array($nguoiTao));

        return parent::setNguoiTao($nguoiTao);
    }

    /**
     * {@inheritDoc}
     */
    public function getNguoiTao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNguoiTao', array());

        return parent::getNguoiTao();
    }

    /**
     * {@inheritDoc}
     */
    public function getTenNguoiTao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTenNguoiTao', array());

        return parent::getTenNguoiTao();
    }

}
