<?php foreach($this->container as $page): ?>
    <?php if(!$page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
    <?php $hasChildren = $page->hasPages(); ?>
    <?php if(!$hasChildren): ?>
        <a href="<?php echo $page->getHref() ?>" class="item <?php if($page->isActive()) echo 'active' ?>">
            <?php echo $page->get('icon'); ?>
            <?php echo $page->getLabel(); ?>
        </a>
    <?php else: ?>
        <div class="link item">
            <?php echo $page->get('icon'); ?>
            <?php echo $page->getLabel(); ?>
            <div class="menu">
                <?php foreach ($page->getPages() as $child): ?>
                    <?php if(!$child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                    <a href="<?php echo $child->getHref(); ?>" class="item <?php if($child->isActive()) echo 'active' ?>">
                        <?php echo $child->getLabel(); ?>
                    </a>
               <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
<?php endforeach; ?>