<?php $user=$this->zfcUserIdentity();?>
<?php $form->setAttribute('action', $this->url('tra_cuu')); ?>
<?php $form->prepare();?>

<?php echo $this->form()->openTag($form);?>
  <div class="ui form">
    <div class="ui celled grid">

      <div class="row">
        <div class="sixteen wide column">
          <div class="inline fields">
            <div class="field">
              <label>Tìm theo hạn xử lý </label>
              <label class="ui large label"> Từ ngày</label>
              <?php echo $this->formJqxDate($form->get('tuNgay')); ?>
            </div>
            <div class="field">
              <label class="ui large label"> đến ngày</label>
              <?php echo $this->formJqxDate($form->get('denNgay')); ?>
            </div>
            <div class="field">
              <input type="submit" class="ui blue button"  style="width:130px;" value="Tìm theo ngày">
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="sixteen wide column">
          <div class="four fields">
            <?php echo $this->formLocRadio($form->get('trangThai')); ?>
          </div>
        </div>
      </div>            

      <div class="row">
        <div class="sixteen wide column">
          <div class="ui menu">
            <div class="menu">
              <div class="item">
                Tìm nhanh
              </div>
              <?php echo $this->formElement($form->get('tieuChi')); ?>
              <div class="item">
                <div class="ui icon input">
                  <?php echo $this->formElement($form->get('tuKhoa')); ?>
                  <i class="search icon"></i>
                </div>
              </div>
              <div class="right item">
                <input type="submit" class="tiny ui button" value="Tìm">
                <input id="xemHet" type="submit"  class="tiny ui button" value="Xem hết">
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
<?php echo $this->form()->closeTag();?>

<?php $trangThai = $form->get('trangThai')->getValue(); ?>
<div class="ui grid"> 
  <div class="sixteen wide column fluid">
    <table class="ui celled structured striped table">
      <thead>
        <tr>    
          <th>STT</th>      
          <th class="four wide">Công văn, người ký</th> 
          <th>Nội dung công việc</th>
          <th>Cơ quan chủ công</th>    
          <th>Hạn xử lý</th>  
          <th>Báo cáo cuối</th>    
        </tr>
      </thead>
      <tbody>
        <?php if(count($congViecs)): ?>
          <?php foreach($congViecs as $i=>$congViec): ?>
          <?php $congVan = $congViec->getCongVan(); ?>
          <tr>
              <?php if($trangThai == 4): ?>
                <?php if($congViec->isQuaHan()): ?>
                  <td class="negative">
                <?php elseif($congViec->getTrangThai() == \CongViec\Entity\CongViec::HOAN_THANH || $congViec->getTrangThai() == \CongViec\Entity\CongViec::TRE_HAN): ?>
                  <td class="positive">
                <?php else: ?>
                  <td>
                <?php endif; ?>
              <?php else: ?>
                <td>
              <?php endif; ?>
                <?php echo $i+1; ?>
              </td>
              <td>
                <div>
                  Số <?php echo $congVan->getSoHieu(); ?> ngày <?php echo $congVan->getNgayBanHanh()->format('d/m/Y'); ?>
                </div>
                <div><?php echo $congVan->getNguoiKy()->getHoTen(); ?></div>
              </td>
              <td>
                <div><a class="ui link" href="<?php echo $this->url('cong_viec/crud', array('action' => 'chi-tiet-cong-viec', 'id' => $congViec->getId())) ?>"><?php echo $congViec->getTen(); ?></a></div>
                <div><i><?php echo $congViec->getNoiDung(); ?></i></div>
              </td>  
              <td>
                <?php if($donVi = $congViec->getDonViChuCong()): ?>
                    <?php echo $donVi->getTenVietTatHoacDayDu(); ?>
                <?php endif; ?>
              </td>
              <td>
                <?php echo $congViec->getNgayHoanThanh()->format('d/m/Y'); ?>
              </td>
              <td>
                <?php if($baoCao = $congViecService->getBaoCaoCuoi($congViec)): ?>
                  <?php echo $baoCao->getNoiDung(); ?>
                <?php endif; ?>
              </td>
            </tr>
          <?php endforeach; ?>
        <?php else: ?>
          <tr>
            <td colspan="6" class="center aligned">Không tìm thấy dữ liệu</td>
          </tr>
        <?php endif; ?>
      </tbody>
    </table>
    <?php echo $this->paginationControl($this->congViecs,
                                    'Sliding',
                                    'paginator/paginator', 
                                    array('route' => 'cong_viec/paginator')); ?>
  </div>
  <?php if($trangThai == 4): //tat ca ?>
  <div class="ui horizontal list">
    <div class="item">
      <div class="ui empty circular label"></div>
      <span>&nbsp;Chưa hoàn thành</span>
    </div>
    <div class="item">
      <div class="ui green empty circular label"></div>
      <span style="color:green;">&nbsp;Đã hoàn thành</span>
    </div>
    <div class="item">
      <div class="ui red empty circular label"></div>
      <span style="color:red;">&nbsp;Quá hạn</span>
    </div>
  </div>
  <?php endif; ?>
  <div class="">
    <a href="#" id="xuatFile" class="ui icon labeled button">
      <i class="print icon"></i>
      Xuất file
    </a>
  </div>
</div>

<script type="text/javascript">

  $(document).ready(function(){
    $('input[name="trangThai"]').change(function(){
      $('#locForm').submit();
    });

    $('#xemHet').click(function(){
      $('input[name="tuKhoa"]').val('');
    });

    $('#xuatFile').click(function(){
      var action = $('#locForm').attr('action');
      $('#locForm').attr('target', '_blank');
      $('#locForm').attr('action', '<?php echo $this->url('ket_xuat/crud', array('action'=>'in-danh-sach-cong-viec')) ?>');
      $('#locForm').submit();
      $('#locForm').attr('action', action);
      $('#locForm').attr('target', '');
    });

  });
  
</script>