<div class="two column row">
  <div class=" left aligned sixteen wide column">
    <div class="divView">        
      
      <div class="ui grid">           
        <div class="sixteen wide column fluid"></div>
        <div class="sixteen wide column fluid">
          <table class="ui table">
            <thead>
              <tr>
                <th>Tên công văn</th>
                <th>Người tạo</th>
                <th>Ngày giao</th>
                <th>Ngày hoàn thành</th>
                
              </tr>
            </thead>
            <tbody>
              
              <tr class="blue">
                <td><a href="chi-tiet-cong-van.html">Xử lý vi phạm pháp luật</a></td>
                <td>Phan Văn Thanh</td>
                <td>23/12/2014</td>
                <td>23/12/2015</td>
       
              </tr> 
              <tr class="purple">
                <td><a href="chi-tiet-cong-van.html">Xử lý vi phạm pháp luật</a></td>
                <td>Phan Văn Thanh</td>
                <td>23/12/2014</td>
                <td>23/12/2015</td>
   
              </tr> 
              <tr class="green">
                <td><a href="chi-tiet-cong-van.html">Xử lý vi phạm pháp luật</a></td>
                <td>Phan Văn Thanh</td>
                <td>23/12/2014</td>
                <td>23/12/2015</td>

              </tr> 
              <tr class="lightred">
                <td><a href="chi-tiet-cong-van.html">Xử lý vi phạm pháp luật</a></td>
                <td>Phan Văn Thanh</td>
                <td>23/12/2014</td>
                <td>23/12/2015</td>

              </tr>   
            </tbody>
          </table>
        </div>
        <div class="right aligned sixteen wide column">                  
          <table align="right">
            <tr style="text-align:left;">
              <td>
                <div class="ui blue empty circular label"></div>
              </td>
              <td>
                <span style="color:blue;">&nbsp;Chưa xem</span>
              </td>
            </tr>
            <tr style="text-align:left;">
              <td>
                <div class="ui purple empty circular label"></div>
              </td>
              <td>
                <span style="color:purple;">&nbsp;Đang xử lý</span>
              </td>
            </tr> 
            <tr style="text-align:left;">
              <td>
                <div class="ui green empty circular label"></div>
              </td>
              <td>
                <span style="color:green;">&nbsp;Hoàn thành</span>
              </td>
            </tr>                    
            <tr style="text-align:left;">
              <td>
                <div class="ui red empty circular label"></div>
              </td>
              <td>
                <span style="color:red;">&nbsp;Trễ hạn</span>
              </td>
            </tr> 
          </table>              
        </div>
      </div>
    </div>
  </div>
</div>  

<script type="text/javascript">
  $(document).ready(function(){
    
  });
</script>