<?php if ($status === true) : ?>
<div class="alert alert-success"><?php echo $this->translate('Thay đổi mật khẩu thành công.');?></div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error"><?php echo $this->translate('Không thể thay đổi mật khẩu. Vui lòng thực hiện lại.'); ?></div>
<?php endif; ?>
<?php
$form = $this->changePasswordForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());
echo $this->form()->openTag($form);
?>

<div class="ui top attached tabular menu">
	<a class="active item" data-tab="first">Thay đổi mật khẩu</a>
</div>	
<div class="ui bottom attached active tab segment" data-tab="first">
	<div class="ui small form segment">
		<div class="fields">
			<div class="four wide field">
				<?php echo $this->formElementErrors($form->get('identity')); ?>
      			<?php echo $this->formInput($form->get('identity')); ?>
			</div>
		</div>
		<div class="fields">
			<div class="four wide field">
				<label>Mật khẩu hiện tại</label>      			
      			<?php
      				$form->get('credential')->setAttribute('autofocus','autofocus');
					echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));
				?>
			</div>
		</div>
		<div class="fields">
			<div class="four wide field">
				<label>Mật khẩu mới</label>      			
      			<?php
					echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));
				?>
			</div>
		</div>
		<div class="fields">
			<div class="four wide field">
				<label>Nhập lại mật khẩu mới</label>      			
      			<?php
					echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));
				?>
			</div>
		</div>
		<div class="fields">&nbsp;</div>
		<div class="fields">
			<div class="four wide field">
				<?php if($this->zfcUserIdentity()->getId()==1){?>
				<a href="<?php echo $this->url('user/crud', array('action'=>'list')); ?>">
				<?php } else {?>
				<a href="<?php echo $this->url('cong_viec');?>">
				<?php } ?>
			  		<input type="button" class="tiny ui button item" value="Trở về">
			  	</a>	  	
			  	<?php
			  		$form->get('submit')->setAttribute('class','tiny ui button item blue');
			  		/*$form->get('submit')->setAttribute('value','Lưu');*/
			  		echo $this->formInput($form->get('submit'));
			  		echo $this->form()->closeTag();
			  	?>
			</div>
		</div>

	</div>
</div>

<?php /*
<h3><?php echo sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName()); ?></h3>
<?php if ($status === true) : ?>
<div class="alert alert-success"><?php echo $this->translate('Password changed successfully.');?></div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
<?php endif; ?>
<?php
$form = $this->changePasswordForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getUsername());
$form->get('credential')->setLabel('Mật khẩu cũ');
$form->get('newCredential')->setLabel('Mật khẩu mới');
$form->get('newCredentialVerify')->setLabel('Xác nhận mật khẩu mới');
$form->get('submit')->setValue('Lưu thông tin')->setAttribute('class', 'ui blue button');
echo $this->form()->openTag($form);
?>
<div class="ui form">
	<div class="ui celled grid">
		<div class="row">
			<div class="sixteen wide column">
				<div class="field">
					<?php echo $this->formLabel($form->get('credential')); ?>
		          	<?php echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));?>
				</div>
				<div class="field">
					<?php echo $this->formLabel($form->get('newCredential')); ?>
		          	<?php echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));?>
				</div>
				<div class="field">
					<?php echo $this->formLabel($form->get('newCredentialVerify')); ?>
		          	<?php echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));?>
				</div>
				<div class="field">
					<?php echo $this->formElementErrors($form->get('identity')); ?>
      				<?php echo $this->formInput($form->get('identity')); ?>
					<?php echo $this->formSubmit($form->get('submit')); ?>
				</div>
			</div>
		</div>
	</div>
</div>
<?php echo $this->form()->closeTag(); ?>
*/?>