<!-- <h3><?php echo sprintf($this->translate('Thay đổi mật khẩu tài khoản %s'), $this->zfcUserDisplayName()); ?></h3> -->
<?php if ($status === true) : ?>
<div class="alert alert-success"><?php echo $this->translate('Thay đổi mật khẩu thành công.');?></div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error"><?php echo $this->translate('Không thể thay đổi mật khẩu. Vui lòng thực hiện lại.'); ?></div>
<?php endif; ?>
<?php
$form = $this->changePasswordForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());
echo $this->form()->openTag($form);
?>


<div class="ui top attached tabular menu">
	<a class="active item" data-tab="first">Thay đổi mật khẩu</a>
</div>	
<div class="ui bottom attached active tab segment" data-tab="first">
<?php
/*
	$form = $this->changePasswordForm;
	$form->prepare();
	$form->setAttribute('action', $this->url('zfcuser/changepassword'));
	$form->setAttribute('method', 'post');
	$emailElement = $form->get('identity');
	$emailElement->setValue($this->zfcUserIdentity()->getEmail());
	echo $this->form()->openTag($form);*/
?>
	<div class="ui small form segment">
		<div class="fields">
			<div class="four wide field">
				<?php echo $this->formElementErrors($form->get('identity')); ?>
      			<?php echo $this->formInput($form->get('identity')); ?>
			</div>
		</div>
		<div class="fields">
			<div class="four wide field">
				<label>Mật khẩu hiện tại</label>      			
      			<?php
					echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));
				?>
			</div>
		</div>
		<div class="fields">
			<div class="four wide field">
				<label>Mật khẩu mới</label>      			
      			<?php
					echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));
				?>
			</div>
		</div>
		<div class="fields">
			<div class="four wide field">
				<label>Nhập lại mật khẩu mới</label>      			
      			<?php
					echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));
				?>
			</div>
		</div>
		<div class="fields">
			<div class="four wide field">
				<?php if($this->zfcUserIdentity()->getId()==1){?>
				<a href="<?php echo $this->url('user/crud', array('action'=>'list')); ?>">
				<?php } else {?>
				<a href="<?php echo $this->url('cong_viec');?>">
				<?php } ?>
			  		<input type="button" class="tiny ui button item" value="Trở về">
			  	</a>	  	
			  	<?php
			  		$form->get('submit')->setAttribute('class','tiny ui button item red');
			  		echo $this->formInput($form->get('submit'));
			  		echo $this->form()->closeTag();
			  	?>
			</div>
		</div>

	</div>
</div>





<!-- <dl class="zend_form">
<?php echo $this->formElementErrors($form->get('identity')); ?>
<dd><?php echo $this->formInput($form->get('identity')); ?></dd>

<dt><?php echo $this->formLabel($form->get('credential')); ?></dt>

<dd><?php
echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));
?></dd>

<dt><?php echo $this->formLabel($form->get('newCredential')); ?></dt>
<dd><?php
echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));
?></dd>

<dt><?php echo $this->formLabel($form->get('newCredentialVerify')); ?></dt>
<dd>
<?php echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));
?>
</dd>

<dd><?php
//echo $this->formInput($form->get('csrf'));
echo $this->formInput($form->get('submit'));
?></dd>

</dl>

<?php echo $this->form()->closeTag(); ?> -->
