<?php if ($status === true) : ?>
<div class="ui success message">
  	<i class="close icon"></i>
  	<div class="header">
   		Thành công
  	</div>
  	<p>Bạn vừa đổi mật khẩu thành công</p>
</div>
<?php elseif ($status === false) : ?>
<!-- <div class="ui error message">
  	<i class="close icon"></i>
  	<div class="header">
   		Thất bại
  	</div>
  	<p>Mật khẩu đăng nhập của bạn chưa được đổi</p>
</div> -->
<?php endif; ?>

<?php
$form = $this->changePasswordForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getUsername());
$form->get('credential')->setLabel('Mật khẩu cũ');
$form->get('newCredential')->setLabel('Mật khẩu mới');
$form->get('newCredentialVerify')->setLabel('Xác nhận mật khẩu mới');
$form->get('submit')->setValue('Lưu thông tin')->setAttribute('class', 'ui blue button');
echo $this->form()->openTag($form);
?>
<div class="ui form">
	<div class="ui celled grid">
		<div class="row">
			<div class="sixteen wide column">
				<div class="field">
					<?php echo $this->formLabel($form->get('credential')); ?>
		          	<?php echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));?>
				</div>
				<div class="field">
					<?php echo $this->formLabel($form->get('newCredential')); ?>
		          	<?php echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));?>
				</div>
				<div class="field">
					<?php echo $this->formLabel($form->get('newCredentialVerify')); ?>
		          	<?php echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));?>
				</div>
				<div class="field">
					<?php echo $this->formElementErrors($form->get('identity')); ?>
      				<?php echo $this->formInput($form->get('identity')); ?>
					<?php echo $this->formSubmit($form->get('submit')); ?>
				</div>
			</div>
		</div>
	</div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    window.setTimeout(function() {
        $(".message").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove(); 
        });
    }, 2000);
</script>