<div id="login" class="container">
<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
 

  <div id="modalDangNhap" class="ui modal small transition visible active" style="margin-top: -154.5px; width:500px;">
      <i class="close icon"></i>
      <div class="header">
        Đăng nhập
      </div>
      <div class="content">
        <div class="ui page grid">
          
          <div class="sixteen wide column">
            <div class="ui form">          
              <div class="required field">
                <label>Email</label>
                <div class="ui icon input">
                  <?php echo $this->formInput($form->get('identity')) ?>
                  <i class="user icon"></i>              
                </div>
                <?php echo $this->formElementErrors($form->get('identity')) ?>
              </div>
              <div class="required field">
                <label>Mật khẩu</label>
                <div class="ui icon input">
                  <?php echo $this->formInput($form->get('credential')) ?>
                  <i class="lock icon"></i>
                </div>
              </div>          
            </div>
         
          </div>
        </div>
      </div>

      <div class="actions">
        <div class="ui button">Hủy</div>
        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>
        <?php $submit = $form->get('submit'); ?>
        <?php $submit->setAttribute('class', 'ui green button'); ?>
        <?php echo $this->formButton($submit) ?>
      </div>
    </div>

<?php echo $this->form()->closeTag() ?>
</div>


  