<?php echo $this->partial('template/flash'); ?>
<div class="ui grid"> 
  	<div class="sixteen wide column fluid">
    	<table class="ui celled structured table">
    		<thead>
    			<th>STT</th>
    			<th>Tên đơn vị</th>
    			<th>Tên viết tắt</th>
    			<th>Số thành viên</th>
    			<th></th>
    		</thead>
    		<tbody>
    			<?php foreach($donVis as $i => $donVi): ?>
    				<tr>
    					<td><?php echo $i+1 ?></td>
    					<td><?php echo $donVi->getTenDonVi(); ?></td>
    					<td><?php echo $donVi->getTenVietTat(); ?></td>
    					<td><?php echo count($donVi->getNhanViens()); ?></td>
    					<td class="center aligned">
                            <a href="<?php echo $this->url('don_vi/crud', array('action'=>'cap-nhat', 'id'=>$donVi->getId())) ?>" class="ui mini icon button" title="Sửa đơn vị"><i class="edit icon"></i></a>
                        </td>
    				</tr>
    			<?php endforeach; ?>
    		</tbody>
    	</table>
        <?php echo $this->paginationControl($this->donVis,
                                    'Sliding',
                                    'paginator/paginator', 
                                    array('route' => 'don_vi/paginator')); ?>
	</div>
</div>