<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Phần mềm quản lý chỉ đạo')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/QuanLyCongVanLayout.css')
                        ->prependStylesheet($this->basePath() . '/vendor/semantic-ui/semantic.css')
                        ->prependStylesheet($this->basePath() . '/vendor/jstree/themes/default/style.css')
                        ->prependStylesheet($this->basePath() . '/vendor/jqwidgets/styles/jqx.base.css')
                       ; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/vendor/semantic-ui/semantic.js')
            ->prependFile($this->basePath() . '/vendor/jstree/jstree.js')

            ->prependFile($this->basePath() . '/vendor/jqwidgets/globalization/globalize.js')
            ->prependFile($this->basePath() . '/vendor/jqwidgets/jqxtooltip.js')
            ->prependFile($this->basePath() . '/vendor/jqwidgets/jqxcalendar.js')
            ->prependFile($this->basePath() . '/vendor/jqwidgets/jqxdatetimeinput.js')
            ->prependFile($this->basePath() . '/vendor/jqwidgets/jqxcore.js')

            ->prependFile($this->basePath() . '/js/script.js')
            ->prependFile($this->basePath() . '/js/QuanLyChiDao.js')
            ->prependFile($this->basePath() . '/js/jquery-2.1.1.min.js')
        ; ?>

    </head>
    <body>
        <div class="ui page grid">
          <div class="sixteen wide column banner">
            <img src="<?php echo $this->basePath();?>/img/baner.png" class="imgBanner">
            <div class="top info">
              <div class="ui small inverted menu">
                <?php if($this->zfcUserIdentity()): ?>                           
                  <a href="<?php echo $this->url('user/crud', array('action'=>'view')); ?>" class="item">
                    Chào <strong><?php echo $this->zfcUserIdentity()->getUsername();?></strong>
                  </a>
                <?php endif; ?> 
                <a href="<?php echo $this->url('zfcuser/logout'); ?>" class="item">Đăng xuất</a>
              </div>
            </div>
          </div>
  
          <div class="ui grid">
            <div class="three wide column">
              <?php $this->navigation('main')->menu()->setPartial('menu/default'); ?>
              <?php echo $this->navigation('main')->menu(); ?>
            </div>
            <div class="thirteen wide column">
              <?php echo $this->content; ?>       
            </div>
          </div>
    
        </div>       
        <?php echo $this->inlineScript() ?>
    </body>
</html>
