<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Phần mềm quản lý chỉ đạo')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/QuanLyCongVanLayout.css')
                        ->prependStylesheet($this->basePath() . '/vendor/semantic-ui/semantic.css')
                       ; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/vendor/semantic-ui/semantic.js')

            ->prependFile($this->basePath() . '/js/script.js')
            ->prependFile($this->basePath() . '/js/QuanLyChiDao.js')
            ->prependFile($this->basePath() . '/js/jquery-2.1.1.min.js')
        ; ?>

    </head>
    <body>
        <div class="ui  page grid">
          <div class="sixteen wide column row center aligned banner">
            <img src="<?php echo $this->basePath();?>/img/baner.png" class="imgBanner">
          </div>
              
          <div class="two column row">
            <div class="four wide column fluid">
              <?php $this->navigation('main')->menu()->setPartial('menu/default'); ?>
              <?php echo $this->navigation('main')->menu(); ?>
            </div>
            <div class="twelve wide column left aligned fluid">
              <div class="sixteen wide column row right aligned">
                <div class="right menu">              
                  <?php
                          if($this->zfcUserIdentity())
                          {?>                                
                              <a href="<?php echo $this->url('user/crud', array('action'=>'list')); ?>"><div class="tiny ui button item"><?php echo 'Chào: '.$this->zfcUserIdentity()->getUsername();?></div></a>
                          <?php }
                      ?>                
                    <a href="<?php echo $this->url('zfcuser/logout'); ?>" style="width:130px; text-align:center;"><div class="tiny ui button item red">Đăng xuất</div></a>
                </div>
              </div> 
              <div class="sixteen wide column row left aligned">
              <?php echo $this->content; ?>
              </div>              
            </div>
          </div>
        </div>       
        <?php echo $this->inlineScript() ?>
    </body>
</html>
<script type="text/javascript">
  $(document).ready(function(){
    $('#accordion').accordion();
  });
  
</script>
