<?php
	echo $this->headTitle('Báo cáo mới');
	$dateTime=new DateTime(null,new DateTimeZone('Asia/Ho_Chi_Minh'));
?>
<div class="sixteen wide column row"><h4 class="ui header">BÁO CÁO MỚI</h4></div>
<?php
	

	if ($this->flashMessenger()->hasMessages()) 
	{
    	echo '<div class="ui negative message">
  				<i id="btFm" class="close icon"></i>
  				<div class="header">';

    	$messages = $this->flashMessenger()->getMessages();
    	foreach($messages as $message) {
        	echo $message;
    	}
    	echo '</div></div>';

    	echo '
	    <script type="text/javascript">
	        setTimeout(function(){
	            document.getElementById("btFm").click();
	        },5000);
	    </script>';
    }	

	$form->setAttribute('action', $this->url('theo_doi/crud', array('action'=>'bao-cao-moi','id'=>$id)));
	$form->prepare();
	echo $this->form()->openTag($form);
	$baoCao=$form->get('theo-doi');
	echo $this->formHidden($baoCao->get('id'));
	$baoCao->get('ngayBaoCao')->setAttribute('value',$dateTime);
	echo $this->formHidden($baoCao->get('ngayBaoCao'));
	$baoCao->get('congVan')->setAttribute('value',$id);
	echo $this->formHidden($baoCao->get('congVan'));
	if($this->zfcUserIdentity()){
		$baoCao->get('nguoiTao')->setAttribute('value',$this->zfcUserIdentity()->getId());
	}
	
	echo $this->formHidden($baoCao->get('nguoiTao'));
?>
	<div class="ui form">
		<div class="fields">
			<div class="sixteen wide field">
			<?php echo $this->formRow($baoCao->get('noiDung')); ?>
			</div>
		</div>
		

		<span><b>Đính kèm</b></span>
		<div class="fields">
			<div class="sixteen wide field">
				
			<?php echo $this->formRow($baoCao->get('dinhKems')); ?>
			</div>
		</div>
	
		<div class="fields">
			<div class="sixteen wide field">				
			<?php	
				$chuTris=$this->ArrayDanhSachNguoiThucHien($nguoiThucHiens);
				$co=0;
				foreach ($chuTris as $key => $chuTri) {
					if($co==0){
						$baoCao->get('nguoiBaoCao')->setAttribute('value',$key);
					}
					$co++;
				}
			 	echo $this->formElement($baoCao->get('nguoiBaoCao'));
			 ?>
			</div>
		</div>
		<br>
		<div class="sixteen wide column row">
			<div class="fields">
				<div class="sixteen wide field">
				<?php
					$form->get('submit')->setAttribute('class','ui button blue');
				 	echo $this->formSubmit($form->get('submit'));
				 ?>
				</div>
			</div>
		</div>
	</div>
<?php
	
	

	echo $this->form()->closeTag();
?>
<script type="text/javascript">
	$(document).ready(function(){
		$('.message .close').on('click', function() {
		  $(this).closest('.message').fadeOut();
		});
	});
</script>