<?php $user=$this->zfcUserIdentity();?>
<?php $form->setAttribute('action', $this->url('cong_viec/crud')); ?>
<?php $form->prepare();?>

<?php echo $this->form()->openTag($form);?>
  <div class="ui form">
    <div class="ui celled grid">

      <div class="row">
        <div class="sixteen wide column">
          <div class="inline fields">
            <div class="field">
              <label>Tìm theo hạn xử lý </label>
              <label class="ui large label"> Từ ngày</label>
              <?php echo $this->formJqxDate($form->get('tuNgay')); ?>
            </div>
            <div class="field">
              <label class="ui large label"> đến ngày</label>
              <?php echo $this->formJqxDate($form->get('denNgay')); ?>
            </div>
            <div class="field">
              <input type="submit" class="ui blue button"  style="width:130px;" value="Tìm theo ngày">
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="sixteen wide column">
          <div class="four fields">
            <?php echo $this->formLocRadio($form->get('trangThai')); ?>
          </div>
        </div>
      </div>            

      <div class="row">
        <div class="sixteen wide column">
          <div class="ui menu">
            <div class="menu">
              <div class="item">
                Tìm nhanh
              </div>
              <?php echo $this->formElement($form->get('tieuChi')); ?>
              <div class="item">
                <div class="ui icon input">
                  <?php echo $this->formElement($form->get('tuKhoa')); ?>
                  <i class="search icon"></i>
                </div>
              </div>
              <div class="right item">
                <input type="submit" class="tiny ui button" value="Tìm">
                <input id="xemHet" type="submit"  class="tiny ui button" value="Xem hết">
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
<?php echo $this->form()->closeTag();?>

<?php $trangThai = $form->get('trangThai')->getValue(); ?>
<div class="ui grid"> 
  <div class="sixteen wide column fluid">
    <table class="ui celled structured table" id="tblTatCa">
      <thead>
        <tr>    
          <th>STT</th>      
          <th class="six wide">Nội dung công việc</th>
          <th class="five wide">Báo cáo mới nhất</th> 
          <th>Chủ trì</th>
          <th>Hạn xử lý</th>       
        </tr>
      </thead>
      <tbody>
        <?php if(count($congViecs)): ?>
          <?php foreach($congViecs as $i=>$congViec): ?>
          <?php $congVan = $congViec->getCongVan(); ?>
          <tr>
              <?php if($trangThai == 4): ?>
                <?php if($congViec->isQuaHan()): ?>
                  <td class="negative">
                <?php elseif($congViec->getTrangThai() == \CongViec\Entity\CongViec::CHUA_XEM): ?>
                  <td class="positive">
                <?php else: ?>
                  <td>
                <?php endif; ?>
              <?php else: ?>
                <td>
              <?php endif; ?>
                <?php echo $i+1; ?>
              </td>
              <td>
                <div><a class="ui link" href="<?php echo $this->url('cong_viec/crud', array('action' => 'chi-tiet-cong-viec', 'id' => $congViec->getId())) ?>"><?php echo $congViec->getTen(); ?></a></div>
                <div><i><?php echo $congViec->getNoiDung(); ?></i></div>
              </td>  
              <td>
                fdsfs
              </td>                    
              <td>
                <?php $user = $congViec->getNguoiChuTri(); ?>
                <?php if($user) echo $user->getHoTen(); ?>
              </td> 
              <td>
                <?php echo $congViec->getNgayHoanThanh()->format('d/m/Y'); ?>
              </td>
            </tr>
          <?php endforeach; ?>
        <?php else: ?>
          <tr>
            <td colspan="6" class="center aligned">Không tìm thấy dữ liệu</td>
          </tr>
        <?php endif; ?>
      </tbody>
    </table>
  </div>
  <?php if($trangThai == 4): //tat ca ?>
    <div class="ui grid">
      <div class="two wide column">
        <div class="ui green empty circular label"></div>
        <span style="color:green;">&nbsp;Chưa xem</span>
      </div>
      <div class="two wide column">
        <div class="ui empty circular label"></div>
        <span>&nbsp;Đang xử lý</span>
      </div>
      <div class="two wide column">
        <div class="ui red empty circular label"></div>
        <span style="color:red;">&nbsp;Quá hạn</span>
      </div>
  </div>
  <?php endif; ?>
</div>

<script type="text/javascript">

  $(document).ready(function(){
    $('input[name="trangThai"]').change(function(){
      $('#locForm').submit();
    });

    $('#xemHet').click(function(){
      $('input[name="tuKhoa"]').val('');
    });

  });
    
</script>