<?php
/*$form = $this->form;
//die(var_dump($form));
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
$emailElement = $form->get('identity');
$emailElement->setValue($this->email);
echo $this->form()->openTag($form);*/
?>

<form action="<?php echo $this->url('user/crud', array('action'=>'changePassWord', 'id'=>$id)) ?>" method="post">
<div class="ui top attached tabular menu">
	<a class="active item" data-tab="first">Thay đổi mật khẩu</a>
</div>	
<div class="ui bottom attached active tab segment" data-tab="first">
	<div class="ui small form segment">
		<div class="fields">
			<div class="four wide field">
				<!-- <input name="identity" value="<?php echo $email;?>" type="hidden"> -->
				<?php //echo $this->formElementErrors($form->get('identity')); ?>
      			<?php //echo $this->formInput($form->get('identity')); ?>
			</div>
		</div>
		<div class="fields">
			<!-- <div class="four wide field">
				<label>Mật khẩu hiện tại</label>   -->    			
      			<!-- <input type="password" name="credential" /> -->
      			<?php
					//echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));
				?>
			</div>
		</div>
		<div class="fields">
			<div class="four wide field">
				<label>Mật khẩu mới</label>      			
      			 <input type="password" name="matKhauMoi" />
      			<?php
					//echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));
				?>
			</div>
		</div>
		<div class="fields">
			<div class="four wide field">
				<label>Nhập lại mật khẩu mới</label>      			
      			<input type="password" name="xacNhanMatKhauMoi" />
      			<?php
					//echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));
				?>
			</div>
		</div>
		<div class="fields">&nbsp;</div>
		<div class="fields">
			<div class="four wide field">
				<input type="submit" value="Lưu">
				<?php
			  		//$form->get('submit')->setAttribute('class','tiny ui button item blue');
			  		//echo $this->formInput($form->get('submit'));
			  		//echo $this->form()->closeTag();
			  	?>
				<?php //if($this->zfcUserIdentity()->getId()==1){?>
				<!-- <a href="<?php //echo $this->url('user/crud', array('action'=>'list')); ?>"> -->
				<?php //} else {?>
				<!-- <a href="<?php //echo $this->url('cong_viec');?>"> -->
				<?php //} ?>
			  		<!-- <input type="button" class="tiny ui button item" value="Trở về">
			  	</a>-->
			  	<?php
			  		/*$form->get('submit')->setAttribute('class','tiny ui button item blue');
			  		echo $this->formInput($form->get('submit'));
			  		echo $this->form()->closeTag();*/
			  	?>
			</div>
		</div>

	</div>
</div>
</form>