<?php
 $title = $users[0]->getDonVi()->getTenDonVi();
 $this->headTitle($title);
 ?> 
 <div class="sixteen wide column row center aligned">
 	<h2><?php echo $this->escapeHtml($title).' - Danh sách tài khoản'; ?></h2>
 </div>

<div class="sixteen wide column fluid">
      <table class="ui table">
        <thead>
          <tr>            
            <th>Tên hiển thị</th>
            <th>Họ</th>
            <th>Tên</th>
            <th>Giới tính</th>
            <th>Điện thoại</th>
            <th>Địa chỉ</th>
            <?php if($this->zfcUserIdentity()->getId()==1){?>            
            <?php } ?>
          </tr>
        </thead>
        <tbody>
        	<?php foreach($users as $user): ?>
				<tr>					
					<td><?php echo $this->escapeHtml($user->getDisplayName()) ?></td>
					<td><?php echo $this->escapeHtml($user->getHo()) ?></td>
					<td><?php echo $this->escapeHtml($user->getTen()) ?></td>
					<td><?php echo $this->escapeHtml($user->getGioiTinh()) ?></td>
					<td><?php echo $this->escapeHtml($user->getDienThoai()) ?></td>
					<td><?php echo $this->escapeHtml($user->getDiaChi()) ?></td>          
				</tr>
				<?php endforeach; ?>
        </tbody>
      </table>
    </div>
