<?php
 $title = $users[0]->getDonVi()->getTenDonVi();
 $this->headTitle($title);
?>  
<div class="ui grid">  
  <div class="nine wide column">    
    <div class="ui header"><?php echo $this->escapeHtml($title); ?></div>
  </div>
  <div class="seven wide column">
    <form method="post" action="<?php echo $this->url('user/crud',array('action'=>'chi-tiet-don-vi')); ?>" onsubmit="return kiemTraTim();">
      <div class="ui icon input">      
      <input placeholder="Tìm nhanh" id="txtDuLieu" name="txtDuLieu" type="text">
      <i class="search icon"></i>
      </div>
      <input class="tiny ui button" name="btnSubmit" id="btnTim" value="Tìm" type="submit">
      <a href="<?php echo $this->url('user/crud',array('action'=>'chiTietDonVi',));?>"><input class="tiny ui button" value="Xem hết" type="button"></a>
    </form>
  </div>
</div>

<div class="sixteen wide column fluid">
      <table class="ui table" style="margin-top:5px;">
        <thead>
          <tr>            
            <th>Tên hiển thị</th>
            <th>Họ</th>
            <th>Tên</th>
            <th>Giới tính</th>
            <th>Điện thoại</th>
            <th>Địa chỉ</th>
            <?php if($this->zfcUserIdentity()->getId()==1){?>            
            <?php } ?>
          </tr>
        </thead>
        <tbody>
        	<?php foreach($users as $user): ?>
				<tr>					
					<td><?php echo $this->escapeHtml($user->getDisplayName()) ?></td>
					<td><?php echo $this->escapeHtml($user->getHo()) ?></td>
					<td><?php echo $this->escapeHtml($user->getTen()) ?></td>
					<td><?php echo $this->escapeHtml($user->getGioiTinh()) ?></td>
					<td><?php echo $this->escapeHtml($user->getDienThoai()) ?></td>
					<td><?php echo $this->escapeHtml($user->getDiaChi()) ?></td>          
				</tr>
				<?php endforeach; ?>
        </tbody>
      </table>
</div>
