<?php
	$dateTime = new DateTime(null, new DateTimeZone('Asia/Ho_Chi_Minh'));
?>
<div class="ui top attached tabular menu">
  <a class="active item" data-tab="first">TẠO TÀI KHOẢN</a>
</div>
<div class="ui bottom attached active tab segment" data-tab="first">
<?php
	$form->setAttribute('action', $this->url('user/crud', array('action'=>'create-account')));
	$form->setAttribute('id','frmCreateAccount');
		$form->setAttribute('onSubmit','return kiemTra();');
	$form->setAttribute('role','form');
	$form->prepare(); 
	echo $this->form()->openTag($form);	      	
	$nguoiDung = $form->get('user');	
	echo $this->formHidden($nguoiDung->get('id'));

	$nguoiDung->get('ngayTao')->setAttribute('value',Date('Y-m-d'));
	echo $this->formHidden($nguoiDung->get('ngayTao'));
	$nguoiDung->get('dangNhapCuoi')->setAttribute('value',Date('Y-m-d'));
	echo $this->formHidden($nguoiDung->get('dangNhapCuoi'));
	$nguoiDung->get('ngayChinhSua')->setAttribute('value',Date('Y-m-d'));
	echo $this->formHidden($nguoiDung->get('ngayChinhSua'));
?>
	<div class="ui small form segment">
	  <div class="fields">
	  	<div class="eight wide field">	      
	      <?php  
	      	$username=$nguoiDung->get('username');
	      	$username->setAttribute('required','required');
	      	$username->setAttribute('autofocus','autofocus');	      	
	      	echo $this->formLabel($username);
	      	echo $this->formElement($username);
	      	if($kiemTraUsername==1)
	      	{
	      		echo "<div class='ui red message'>Tên đăng nhập đã được sử dụng</div>";	      		
	      	}
	      ?>
	    </div>
	  </div>
	  <div class="fields">
	  	<div class="four wide field">
	  		<?php 
	  			$password=$nguoiDung->get('password');
	  			$password->setAttribute('required','required');
	  			$password->setAttribute('id','pass');
	      		$password->setAttribute('type','password');
	  		?>
	  		<?php echo $this->formLabel($password); ?>
	      	<?php echo $this->formElement($password); ?>
	      	<?php echo $this->formElementErrors($password); ?>	      
	    </div>	    
	  </div>

	  <div class="fields">
	  	<div class="four wide field">
	      <label>Nhập lại mật khẩu</label>
	      <input type="password" id="passVerify" required="required" placeholder ='Nhập lại mật khẩu'/>
	    </div>	    
	  </div>
	  <div class="fields">
		<div id="kiemTraMatKhau" class='ui red message eight wide field' hidden></div>	
	  </div>

	  <div class="fields">
	    <div class="four wide field">
	      <?php $nguoiDung->get('ho')->setAttribute('required','required');?>
	  		<?php echo $this->formLabel($nguoiDung->get('ho')); ?>
	      	<?php echo $this->formElement($nguoiDung->get('ho')); ?>
	      	<?php echo $this->formElementErrors($nguoiDung->get('ho')); ?>
	    </div>
	    <div class="four wide field">
	    	<?php $nguoiDung->get('ten')->setAttribute('required','required');?>
	  		<?php echo $this->formLabel($nguoiDung->get('ten')); ?>
	      	<?php echo $this->formElement($nguoiDung->get('ten')); ?>
	      	<?php echo $this->formElementErrors($nguoiDung->get('ten')); ?>	      
	    </div>
	   </div>
	  <div class="field">
	  	  <?php echo $this->formLabel($nguoiDung->get('gioiTinh')); ?>
	      <div class="ui form">
			  <div class="inline fields">
			    <?php 
			    	$nguoiDung->get('gioiTinh')->setValue(1);
			    	echo $this->formRadio($nguoiDung->get('gioiTinh')); 
			    ?>
			  </div>			  
			</div>
	  </div>

	  <div class="fields">
	  	<div class="four wide field">
	  		<?php $nguoiDung->get('displayName')->setAttribute('required','required');?>
	  		<?php echo $this->formLabel($nguoiDung->get('displayName')); ?>
	      	<?php echo $this->formElement($nguoiDung->get('displayName')); ?>
	      	<?php echo $this->formElementErrors($nguoiDung->get('displayName')); ?>	      
	    </div>
	    <div class="four wide field">
	    	<?php $nguoiDung->get('dienThoai')->setAttribute('required','required');?>
	    	<?php $nguoiDung->get('dienThoai')->setAttribute('id','dienThoai');?>
	    	<?php $nguoiDung->get('dienThoai')->setAttribute('type','number');?>	    	
	  		<?php echo $this->formLabel($nguoiDung->get('dienThoai')); ?>
	      	<?php echo $this->formElement($nguoiDung->get('dienThoai')); ?>
	      	<?php echo $this->formElementErrors($nguoiDung->get('dienThoai')); ?>	      
	      <?php	      	
	      	if($kiemTraSoDienThoai==1)
	      	{
	      		echo "<div class='ui red message'>Số điện thoại đã sử dụng</div>";	      		
	      	}
	      ?>
	      <div id="kiemTraDienThoai" class='ui red message sixteen wide field' hidden></div>
	  	</div>
	  </div>

	  <div class="fields">
	  	<div class="eight wide field">
	  		<?php $nguoiDung->get('diaChi')->setAttribute('required','required');?>
	  		<?php echo $this->formLabel($nguoiDung->get('diaChi')); ?>
	      	<?php echo $this->formElement($nguoiDung->get('diaChi')); ?>
	      	<?php echo $this->formElementErrors($nguoiDung->get('diaChi')); ?>	      
	    </div>
	  </div>

	  <div class="fields">
	  	<div class="eight wide field">
	      <?php $nguoiDung->get('email')->setAttribute('required','required');?>
	  		<?php echo $this->formLabel($nguoiDung->get('email')); ?>
	      	<?php echo $this->formElement($nguoiDung->get('email')); ?>
	      	<?php echo $this->formElementErrors($nguoiDung->get('email')); ?>
	      <?php	      	
	      	if($kiemTraEmail==1)
	      	{
	      		echo "<div class='ui red message'>Email đã được sử dụng</div>";	      		
	      	}
	      ?>	      
	    </div>
	  </div>
	  <div class="fields">
	  	<div class="eight wide field">
	  		<?php echo $this->formLabel($nguoiDung->get('donVi')); ?>
	      	<?php echo $this->formElement($nguoiDung->get('donVi')); ?>
	      	<?php echo $this->formElementErrors($nguoiDung->get('donVi')); ?>	      
		</div>
	  </div>

	  </div>	  
	  <div class="fields">&nbsp;</div>
	  <div class="fields">	  	
		<a href="<?php echo $this->url('user/crud', array('action'=>'list')); ?>">		
	  		<input type="button" class="tiny ui button item" value="Trở về">
	  	</a>	  	
	  	<?php
	  		$form->get('submit')->setAttribute('class','tiny ui button item blue');
	  		echo $this->formSubmit($form->get('submit'));
	  		echo $this->form()->closeTag();
	  	?>	  	
	  </div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	$('.menu .item').tab();

	$('.ui.radio.checkbox').checkbox();

	$('select.dropdown').dropdown();
});

$('.message .close').on('click', function() {
  $(this).closest('.message').fadeOut();
});

</script>

<script type="text/javascript">
	kiemTra=function()
	{
		document.getElementById("kiemTraMatKhau").hidden=true;
		document.getElementById("kiemTraDienThoai").hidden=true;
		document.getElementById("kiemTraDienThoai").hidden=true;
		var pass=document.getElementById('pass');		
		var passVerify=document.getElementById('passVerify');
		var dienThoai=document.getElementById('dienThoai');

		if((pass.value).length<6||(passVerify.value).length<6)
		{
			document.getElementById("kiemTraMatKhau").hidden=false;		
			$('#kiemTraMatKhau').text('Vui lòng nhập mật khẩu có tối thiểu 6 ký tự');
			return false;
		}

		if((dienThoai.value).length<10||(dienThoai.value).length>11)
		{
			document.getElementById("kiemTraDienThoai").hidden=false;		
			$('#kiemTraDienThoai').text('Số điện thoại dài 10 hoặc 11 ký tự');
			return false;
		}

		if(pass.value==passVerify.value)
		{
			document.getElementById('frmCreateAccount').submit();
			return true;
		}
		else
		{			
			document.getElementById("kiemTraMatKhau").hidden=false;		
			$('#kiemTraMatKhau').text('Xác nhận mật khẩu không chính xác');
			return false;
		}		
	}
</script>