<?php

 $title = 'Danh mục đơn vị';
 $this->headTitle($title);
 ?> 
 <div class="sixteen wide column row center aligned">
 	<h2>DANH MỤC ĐƠN VỊ</h2>
 </div>
<div class="sixteen wide column row right aligned">
  <div class="fields">
    <form method="post" action="<?php echo $this->url('user/crud',array('action'=>'danhMucDonVi')); ?>" onsubmit="return kiemTraTim();">
      <div class="ui icon input">      
      <input placeholder="Tìm nhanh" id="txtDuLieu" name="txtDuLieu" type="text">
      <i class="search icon"></i>
      </div>
      <input class="tiny ui button" name="btnSubmit" id="btnTim" value="Tìm" type="submit">
      <a href="<?php echo $this->url('user/crud',array('action'=>'danhMucDonVi'));?>"><input class="tiny ui button" value="Xem hết" type="button"></a>
    </form>
  </div>
 </div>
<div class="sixteen wide column fluid">
      <table class="ui table">
        <thead>
          <tr>            
            <th>Tên đơn vị</th>
            <th>Số thành viên</th>            
          </tr>
        </thead>
        <tbody>
        <?php 
          if($kiemTraDonVi==1)
          {          
            $i=0;
            foreach($donVis as $donVi) {
          ?>
  				<tr>					
  					<td>
              <?php if((int)($listCount[$i])>0){?>
              <a href="<?php echo $this->url('user/crud', array('action'=>'chiTietDonVi', 'id'=>$donVi->getId())) ?>"><?php echo $donVi->getTenDonVi();?></a>
              <?php }else
                {
                  echo $donVi->getTenDonVi();
                }?>              
            </td>
            <td><?php echo $this->escapeHtml($listCount[$i]);?></td>
  				</tr>
          <?php 
            $i++;}
          }
          else {?>
            <tr><td>Danh sách đơn vị trống</td></tr>
          <?php }?>
        </tbody>
      </table>
</div>

<script type="text/javascript">
  kiemTraTim=function()
  {
    var txtDuLieu=document.getElementById('txtDuLieu');
    if(txtDuLieu.value==''||txtDuLieu.value==null)
    {
      return false;
    }
    else
      return true;
  }
</script>
