<?php
 $title = 'Danh mục đơn vị';
 $this->headTitle($title);
 if ($this->flashMessenger()->hasMessages()) 
  {
      echo '<div class="ui positive message">
          <i id="btFm" class="close icon"></i>
          <div class="header">';

      $messages = $this->flashMessenger()->getMessages();
      foreach($messages as $message) {
          echo $message;
      }
      echo '</div></div>';

      echo '
      <script type="text/javascript">
          setTimeout(function(){
              document.getElementById("btFm").click();
          },5000);
      </script>';
  } 
?>
<div class="sixteen wide column row center aligned">
 	<h2>DANH MỤC ĐƠN VỊ</h2>
 </div>
<div class="ui grid">  
  <div class="nine wide column">
    <a href="<?php echo $this->url('user/crud', array('action'=>'tao-don-vi')) ?>">
        <input class="tiny ui button item blue" value="Tạo đơn vị" type="button">
    </a>
  </div>
  <div class="seven wide column">
    <form method="post" action="<?php echo $this->url('user/crud',array('action'=>'danhMucDonVi')); ?>" onsubmit="return kiemTraTim();">
      <div class="ui icon input">      
      <input placeholder="Tìm nhanh" id="txtDuLieu" name="txtDuLieu" type="text" autofocus>
      <i class="search icon"></i>
      </div>
      <input class="tiny ui button" name="btnSubmit" id="btnTim" value="Tìm" type="submit">
      <a href="<?php echo $this->url('user/crud',array('action'=>'danhMucDonVi'));?>"><input class="tiny ui button" value="Xem hết" type="button"></a>
    </form>
  </div>
</div>

<div class="sixteen wide column fluid">
  <table class="ui table">
        <thead>
          <tr>            
            <th>Tên đơn vị</th>
            <th>Số thành viên</th>
            <th>Cập nhật</th>            
          </tr>
        </thead>
        <tbody>
        <?php 
          if($kiemTraDonVi==1)
          {          
            $i=0;
            foreach($donVis as $donVi) {
          ?>
  				<tr>					
  					<td>
              <?php if((int)($listCount[$i])>0){?>
              <a href="<?php echo $this->url('user/crud', array('action'=>'chiTietDonVi', 'id'=>$donVi->getId())) ?>"><?php echo $donVi->getTenDonVi();?></a>
              <?php }else
                {
                  echo $donVi->getTenDonVi();
                }?>              
            </td>
            <td><?php echo $this->escapeHtml($listCount[$i]);?></td>
            <td>          
              <a href="<?php echo $this->url('user/crud', array('action'=>'sua-don-vi', 'id'=>$donVi->getId())) ?>" title="Sửa tên đơn vị"><i class="edit icon"></i></a>            
            </td>
  				</tr>
          <?php 
            $i++;}
          }
          else {?>
            <tr><td>Danh sách đơn vị trống</td></tr>
          <?php }?>
        </tbody>
  </table>
</div>

<script type="text/javascript">
$(document).ready(function(){
  $('.menu .item').tab();

  $('.ui.radio.checkbox').checkbox();

  $('select.dropdown').dropdown();
});

$('.message .close').on('click', function() {
  $(this).closest('.message').fadeOut();
});
</script>

<script type="text/javascript">
  kiemTraTim=function()
  {
    var txtDuLieu=document.getElementById('txtDuLieu');
    if(txtDuLieu.value==''||txtDuLieu.value==null)
    {
      return false;
    }
    else
      return true;
  }
</script>
