<?php

 $title = 'Danh mục đơn vị';
 $this->headTitle($title);
 ?> 
 <div class="sixteen wide column row center aligned">
 	<h2>DANH MỤC ĐƠN VỊ</h2>
 </div>

<div class="sixteen wide column fluid">
      <table class="ui table">
        <thead>
          <tr>            
            <th>Tên đơn vị</th>
            <th>Số thành viên</th>            
          </tr>
        </thead>
        <tbody>
        <?php 
          if($kiemTraDonVi==1)
          {          
            $i=0;
            foreach($donVis as $donVi) {
          ?>
  				<tr>					
  					<td>
              <?php if((int)($listCount[$i])>0){?>
              <a href="<?php echo $this->url('user/crud', array('action'=>'chiTietDonVi', 'id'=>$donVi->getId())) ?>"><?php echo $donVi->getTenDonVi();?></a>
              <?php }else
                {
                  echo $donVi->getTenDonVi();
                }?>              
            </td>
            <td><?php echo $this->escapeHtml($listCount[$i]);?></td>
  				</tr>
          <?php 
            $i++;}
          }
          else {?>
            <tr><td>Danh sách đơn vị trống</td></tr>
          <?php }?>
        </tbody>
      </table>
    </div>
