<?php

 $title = 'EDIT USER';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('user/crud', array('action'=>'edit','id' => $id)));
$form->prepare();

echo $this->form()->openTag($form);
$user = $form->get('user');
echo $this->formRow($user->get('phoneNumber'));
echo $this->formRow($user->get('displayName'));
echo $this->formRow($user->get('address'));

echo $this->formHidden($user->get('id'));
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();