<div class="ui celled grid">
	<div class="row">
		<div class="four wide column right aligned">
			<strong>Họ tên</strong>
		</div>
		<div class="twelve wide column">
			<?php echo $user->getHoTen(); ?>
		</div>
	</div>
	<div class="row">
		<div class="four wide column right aligned">
			<strong>Giới tính</strong>
		</div>
		<div class="twelve wide column">
			<?php echo $user->getGioiTinh(); ?>
		</div>
	</div>
	<div class="row">
		<div class="four wide column right aligned">
			<strong>Điện thoại</strong>
		</div>
		<div class="twelve wide column">
			<?php echo $user->getDienThoai(); ?>
		</div>
	</div>
	<div class="row">
		<div class="four wide column right aligned">
			<strong>Email</strong>
		</div>
		<div class="twelve wide column">
			<?php echo $user->getEmail(); ?>
		</div>
	</div>
	<div class="row">
		<div class="four wide column right aligned">
			<strong>Địa chỉ</strong>
		</div>
		<div class="twelve wide column">
			<?php echo $user->getDiaChi(); ?>
		</div>
	</div>
	<div class="row">
		<div class="four wide column right aligned">
			<strong>Đơn vị</strong>
		</div>
		<div class="twelve wide column">
			<?php echo $user->getTenDonVi(); ?>
		</div>
	</div>
</div>