<?php

 $title = 'USERS';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
	<tr>
		<th>Điện thoại</th>
		<th>Tên</th>
		<th>Địa chỉ</th>
		<th></th>
	</tr>	
	<?php foreach($users as $user): ?>
	<tr>
		<td><?php echo $this->escapeHtml($user->getDienthoai()) ?></td>
		<td><?php echo $this->escapeHtml($user->getTen()) ?></td>
		<td><?php echo $this->escapeHtml($user->getDiaChi()) ?></td>
		<td><a href="<?php echo $this->url('user/crud', array('action'=>'edit', 'id'=>$user->getId())) ?>">Sửa</a></td>
	</tr>
	<?php endforeach; ?>
</table>