<?php  
  $title = 'Tài khoản';
  $this->headTitle($title);

  if ($this->flashMessenger()->hasMessages()) 
  {
      echo '<div class="ui positive message">
          <i id="btFm" class="close icon"></i>
          <div class="header">';

      $messages = $this->flashMessenger()->getMessages();
      foreach($messages as $message) {
          echo $message;
      }
      echo '</div></div>';

      echo '
      <script type="text/javascript">
          setTimeout(function(){
              document.getElementById("btFm").click();
          },5000);
      </script>';
  } 
?> 
 <div class="sixteen wide column row center aligned">
  <h2>TÀI KHOẢN</h2>
 </div>
<div class="sixteen wide column row right aligned">
  <div class="fields">
    <form method="post" action="<?php echo $this->url('user/crud',array('action'=>'list')); ?>" onsubmit="return kiemTraTim();">
      <div class="ui icon input">      
      <input placeholder="Tìm nhanh" id="txtDuLieu" name="txtDuLieu" type="text" autofocus>      
      <i class="search icon"></i>
      </div>
      <input class="tiny ui button" name="btnSubmit" id="btnTim" value="Tìm" type="submit">
      <a href="<?php echo $this->url('user/crud',array('action'=>'list'));?>"><input class="tiny ui button" value="Xem hết" type="button"></a>
    </form>
  </div>
 </div>
        
<div class="sixteen wide column fluid">
    <table class="ui table">
      <thead>
        <tr>            
          <th>Tên hiển thị</th>
          <th>Họ</th>
          <th>Tên</th>
          <th>Giới tính</th>
          <th>Điện thoại</th>
          <th>Địa chỉ</th>
          <?php if($this->zfcUserIdentity()->getId()==1){?>
          <th>Cập nhật</th>
          <?php } ?>
        </tr>
      </thead>
      <tbody>
      	<?php foreach($users as $user): ?>
			<tr>					
				<td><?php echo $this->escapeHtml($user->getDisplayName()) ?></td>
				<td><?php echo $this->escapeHtml($user->getHo()) ?></td>
				<td><?php echo $this->escapeHtml($user->getTen()) ?></td>
				<td><?php echo $this->escapeHtml($user->getGioiTinh()) ?></td>
				<td><?php echo $this->escapeHtml($user->getDienThoai()) ?></td>
				<td><?php echo $this->escapeHtml($user->getDiaChi()) ?></td>
        
        <?php if($this->zfcUserIdentity()->getId()==1){?>
				<td>          
          <a href="<?php echo $this->url('user/crud', array('action'=>'update', 'id'=>$user->getId())) ?>" title="Sửa thông tin"><i class="edit icon"></i></a>            
        </td>
        <?php } ?>
			</tr>
			<?php endforeach; ?>
      </tbody>
    </table>
</div>
    
<script type="text/javascript">
$('.message .close').on('click', function() {
  $(this).closest('.message').fadeOut();
});
</script>
<script type="text/javascript">
  kiemTraTim=function()
  {
    var txtDuLieu=document.getElementById('txtDuLieu');
    if(txtDuLieu.value==''||txtDuLieu.value==null)
    {
      return false;
    }
    else
      return true;
  }
</script>