<div class="ui top attached tabular menu">
  <a class="active item" data-tab="first">Cập nhật thông tin cá nhân</a>
  <a class="item" data-tab="second">Thay đổi mật khẩu</a>  
</div>

<div class="ui bottom attached active tab segment" data-tab="first">
  <!--  -->
	<div class="ui small form segment">
	  <div class="tree fields">
	    <div class="field">
	      <label>Họ</label>
	      <input placeholder="Họ" type="text">
	    </div>
	    <div class="field">
	      <label>Tên</label>
	      <input placeholder="Tên" type="text">
	    </div>

	    <div class="field">
	      <label>Giới tính</label>
		  <div class="ui radio checkbox">
	        <input name="gioiTinh" checked="" type="radio">
	        <label>Nam</label>
	      </div>

	      <div class="ui radio checkbox">
	        <input name="gioiTinh" checked="" type="radio">
	        <label>Nữ</label>
	      </div>
	    </div>
	  </div>
	  <div class="ui submit button">Submit</div>
	</div>	
  <!--  -->

 <div class="ui form">
 	<!-- <div class="inline fields">
    	<label for="fruit">Giới tính</label>
    	<div class="field">
      <div class="ui radio checkbox">
        <input name="gioiTinh" checked="" type="radio">
        <label>Nam</label>
      </div>
    	</div>
    	<div class="field">
      <div class="ui radio checkbox">
        <input name="gioiTinh" type="radio">
        <label>Nữ</label>
      </div>
    	</div>    
  	</div> -->  
 </div>

</div>

<div class="ui bottom attached tab segment" data-tab="second">
  Second
</div>

<script type="text/javascript">
$(document).ready(function(){
	$('.menu .item').tab();

	$('.ui.radio.checkbox').checkbox();

	$('select.dropdown').dropdown();
});
</script>