<?php /*
$form->setAttribute('action', $this->url('user/crud', array('action'=>'update','id' => $id)));
$form->prepare();?>

<?php
echo $this->form()->openTag($form);
$user = $form->get('user');
?>
	<div class="field">
		<?php echo $this->formLabel($user->get('donVi')); ?>
      	<?php echo $this->formElement($user->get('donVi')); ?>
      	<?php echo $this->formElementErrors($user->get('donVi')); ?>
	</div>
	<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); */?>

<?php
	if ($this->flashMessenger()->hasMessages()) 
	{
    	echo '<div class="ui positive message">
  				<i id="btFm" class="close icon"></i>
  				<div class="header">';

    	$messages = $this->flashMessenger()->getMessages();
    	foreach($messages as $message) {
        	echo $message;
    	}
    	echo '</div></div>';

    	echo '
	    <script type="text/javascript">
	        setTimeout(function(){
	            document.getElementById("btFm").click();
	        },5000);
	    </script>';
    }	
?>
<div class="ui top attached tabular menu">
  <a class="active item" data-tab="first">Cập nhật thông tin cá nhân</a>
</div>

<div class="ui bottom attached active tab segment" data-tab="first">
	<?php
  	$form->setAttribute('action', $this->url('user/crud', array('action'=>'update','id' => $id)));
	$form->setAttribute('role','form');
	$form->prepare(); 
  	echo $this->form()->openTag($form);
  	$nguoiDung = $form->get('user');   	
	echo $this->formHidden($nguoiDung->get('id'));
	echo $this->formHidden($nguoiDung->get('username'));
	echo $this->formHidden($nguoiDung->get('password'));
	echo $this->formHidden($nguoiDung->get('gioiTinh'));
	echo $this->formHidden($nguoiDung->get('ngayTao'));
	echo $this->formHidden($nguoiDung->get('dangNhapCuoi'));
	echo $this->formHidden($nguoiDung->get('ngayChinhSua')); ?>
	<div class="ui small form segment">
	  <div class="fields">
	    <div class="four wide field">
	      <label>Họ</label>
	      <?php
	      	$ho=$nguoiDung->get('ho');
	      	$ho->setAttribute('required','required');
	      	echo $this->formElement($ho); 
	      ?> 
	    </div>
	    <div class="four wide field">
	      <label>Tên</label>	      
	      <?php 
	      	$ten=$nguoiDung->get('ten');
	      	$ten->setAttribute('required','required');
	      	echo $this->formElement($ten); 
	      ?> 
	    </div>
	   </div>
	   <div class="field">
	      <label>Giới tính</label>
		  <?php
		  	if($nguoiDung->get('gioiTinh')->getValue()=='Nam')
		  	{?>
		  		<div class="ui radio checkbox">
		  			<input name="gioiTinh" value="Nam" checked="checked" type="radio">
		  			<label>Nam</label>
		  		</div>
		  		<div class="ui radio checkbox">
			        <input name="gioiTinh" value="Nu" type="radio">
			        <label>Nữ</label>
			    </div>
		  <?php }
		  	else
		  	{?>
		  		<div class="ui radio checkbox">
		  			<input name="gioiTinh" value="Nam" type="radio">
		  			<label>Nam</label>
		  		</div>
		  		<div class="ui radio checkbox">
			        <input name="gioiTinh" value="Nu" checked="checked" type="radio">
			        <label>Nữ</label>
			    </div>
		  	<?php }
		  ?>	    
	  </div>

	  <div class="fields">
	  	<div class="four wide field">
	      <label>Tên hiển thị</label>
	      <?php 
	      	$displayName=$nguoiDung->get('displayName');
	      	echo $this->formElement($displayName); 
	      ?>
	    </div>
	    <div class="four wide field">
	      <label>Điện thoại</label>
	      <?php 
	      	$dienThoai=$nguoiDung->get('dienThoai');	      	
	      	echo $this->formElement($dienThoai); 
	      ?> 
	  	</div>
	  </div>

	  <div class="fields">
	  	<div class="eight wide field">
	      <label>Địa chỉ</label>
	      <?php 
	      	$diaChi=$nguoiDung->get('diaChi');	      	
	      	echo $this->formElement($diaChi);	      	
	      ?>
	    </div>
	  </div>

	  <div class="fields">
	  	<div class="eight wide field">
	      <label>Email</label>
	      <?php 
	      	$email=$nguoiDung->get('email');
	      	$email->setAttribute('required','required');	      	
	      	echo $this->formElement($email);
	      	if($kiemTraEmail==1)
	      	{
	      		echo "<div class='ui red message'>Email đã được sử dụng</div>";	      		
	      	}
	      ?>	      
	    </div>
	  </div>
	  <div class="fields">
	  	<div class="eight wide field">
		      	<?php echo $this->formLabel($nguoiDung->get('donVi')); ?>
		      	<?php echo $this->formElement($nguoiDung->get('donVi')); ?>
		      	<?php echo $this->formElementErrors($nguoiDung->get('donVi')); ?>			  
		</div>
	  </div>
	  <div class="fields">
	  	<div class="eight wide field">
	      <a href="<?php echo $this->url('user/crud', array('action'=>'adminChangePassWord', 'id'=>$id)) ?>">Thay đổi mật khẩu</a>		      
	    </div>
	  </div>
	  <div class="fields">&nbsp;</div>
	  <div class="fields">	  	
		<a href="<?php echo $this->url('user/crud', array('action'=>'list')); ?>">		
	  		<input type="button" class="tiny ui button item" value="Trở về">
	  	</a>	  	
	  	<?php
	  		$form->get('submit')->setAttribute('class','tiny ui button item blue');
	  		echo $this->formSubmit($form->get('submit'));
	  		echo $this->form()->closeTag();
	  	?>	  	
	  </div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	$('.menu .item').tab();

	$('.ui.radio.checkbox').checkbox();

});

$('.message .close').on('click', function() {
  $(this).closest('.message').fadeOut();
});
</script>