<div class="ui celled grid">
	<div class="row">
		<div class="four wide column right aligned">
			<strong>Tên phần mềm</strong>
		</div>
		<div class="twelve wide column">
			Phần mềm quản lý chỉ đạo
		</div>
	</div>
	<div class="row">
		<div class="four wide column right aligned">
			<strong>Phiên bản</strong>
		</div>
		<div class="twelve wide column">
			v1.0.1
		</div>
	</div>
	<div class="row">
		<div class="four wide column right aligned">
			<strong>Liên hệ hỗ trợ</strong>
		</div>
		<div class="twelve wide column">
			0987 309 606 - hsqtravinh@gmail.com
		</div>
	</div>
</div>