<div class="ui celled grid">
    <div class="row">
        <div class="eight wide column">
            <h4 class="ui header">Công việc mới</h4>
            <?php var_dump($congViecs); ?>
        </div>
        <div class="eight wide column">
            <h4 class="ui header">Báo cáo mới</h4>
            <?php var_dump($baoCaos); ?>
        </div>
    </div>
    <div class="row">
        <div class="eight wide column">
            <h4 class="ui header">Công việc sắp hết hạn</h4>
            <?php var_dump($sapHetHans); ?>
        </div>
        <div class="eight wide column">
            <h4 class="ui header">Công việc trễ hạn</h4>
            <?php var_dump($treHans); ?>
        </div>
    </div>
</div>